nod-ai/iree-amd-aie

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

Adds a place holder IREE::HAL::ExecutableTargetAttr to unblock Codegen effort
Fixes: https://github.com/nod-ai/iree-amd-aie/issues/1

[AMDAIE] Add getExecutableTargets function in AIETarget.cpp

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
tests/samples/matmul_codegen_spec_pack.mlir
tests/samples/matmul_static.mlir

This PR does not add an end-to-end flow yet, because it does not serialize the executable. This just enables the use of transform dialect and add some examples.

Add support for using transform dialect scripts on AIE backend.

---

compiler/plugins/target/AMD-AIE/Translation/AIESerializer.cpp

I hit the deprecation error with the following setup:
iree, iree-amd-aie: both on main branch, pulled afternoon of Nov 14

Fix dyn_cast compiler deprecation error

---

runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/direct_allocator.h
runtime/src/iree-amd-aie/driver/xrt/nop_semaphore.cc
runtime/src/iree-amd-aie/driver/xrt/nop_semaphore.h
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.h
runtime/src/iree-amd-aie/driver/xrt/xrt_driver.cc

- Add device
- Add some dump information and driver query functions
- Add event semaphore and creates it from device, although I dont think these will be used by the runtime in the near future
- (we will add a blocking sync call in queue execute in the near future when we implement queue functions next, provide thread per queue in the mid future and eventually do a full async execution

Add XRT device and wire it up with the driver, add event semaphore

---

compiler/plugins/target/AMD-AIE/aie/AIETransformPasses.cpp
compiler/plugins/target/AMD-AIE/aie/AIEXTransformPasses.cpp
compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/aie/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h

This patch adds more passes to start preparing for binary conversion (based on
https://github.com/Xilinx/mlir-aie/blob/main/python/compiler/aiecc/main.py)

Add more passes to enable AIE -> Binary translation.

---

compiler/plugins/target/AMD-AIE/aie/AIETransformPasses.cpp
compiler/plugins/target/AMD-AIE/aie/AIEXTransformPasses.cpp
compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
tests/samples/matmul_fill_static_i32.mlir

This does not get us all the way to binary, but the sample lowers to LLVM successfully.
Next step is to generate the actual binaries.

Add passes to lower AIE Device code to LLVM.

---

compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/PeanoToolKit.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/PeanoToolKit.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
tests/samples/matmul_fill_static_i32.mlir

This commits adds the initial plumbing to generate binaries for AIE target using Peano.
1) Adds an option iree-amd-aie-peano-install-dir which can point to
the Peano installation directory. The serialization then uses `opt`
and `llc` from the installation directory to generate the core binary.
2) Generates the binary that represents the ShimDMA instructions.
3) Adds all the passes used in
https://github.com/Xilinx/mlir-aie/blob/main/python/compiler/aiecc/main.py
to prepare for lowering to LLVM and the actual translation to LLVM
IR to AIETarget. They are moved out of the translation passes to
keep the flow consistent with what is done in AIR-AIE.

Initial commit for generating binaries for AIE target. 

---

compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/PeanoToolKit.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/PeanoToolKit.h

The AIE Core elf generation needs mlir-aie installation. So this PR
adds a flag `iree-amd-aie-mlir-aie-install-dir` that needs to point to
the MLIR-AIE installation path. This is meant to be a temporary
situation for initial binary generation prototyping.
Refactor some of the serialization logic to allow for cloning of the
ModuleOp. This is required since the same initial module is used in
multiple binary generation flows.

Add core elf-generation methods. 

---

compiler/plugins/target/AMD-AIE/air/CMakeLists.txt

Steps taken:
- Moved nod.ai/mlir-air/iree_fixes changes to xilinx/mlir-air/main where possible : https://github.com/Xilinx/mlir-air/pull/359
- Squashed remaining changes into a single commit, created branch iree_fixes_3 which has this commit on top of xilinx/mlir-air/main : https://github.com/nod-ai/mlir-air/tree/iree_fixes_3 
- Created this PR

Change the mlir-air submodule branch (from iree_fixes to iree_fixes_3)

---

compiler/plugins/target/AMD-AIE/aie/AIETransformPasses.cpp
compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XclBinGeneratorKit.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XclBinGeneratorKit.h

With this PR the binary translation adds all the functionality needed to generate the two binary pieces that IREE needs to generate. To get here  a new option, `--iree-amd-aie-vitis-install-dir`, was needed to point to the Vitis installation directory to pick up the libraries and binaries needed for the final xclbin generation.
This effectively now is capable of replicating the flow in aiecc.py using the following command
```
SAMPLES_DIR=<iree-amd-aie source dir>/tests/samples
iree-compile  --iree-hal-target-backends=amd-aie  \
${SAMPLES_DIR}/matmul_fill_static_i32.mlir \
--iree-codegen-transform-dialect-library=${SAMPLES_DIR}/matmul_fill_spec_pad.mlir \
--iree-amd-aie-peano-install-dir=<peano installation directory> \
--iree-amd-aie-mlir-aie-install-dir=<mlir-aie installation directory> …
```

Finishing up xclbin generation.

---

compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
compiler/plugins/target/AMD-AIE/air/TransformPasses.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

New MLIR-AIR features:
- air.channels can now pack parent perfectly nested loops into its sizes and strides fields.
- Packed air.channels can now lower to AIE DMA BDs to pick up the implicit loops.
- Enabled bigger lowerable matmul sizes.

Bump MLIR-AIR version

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

This PR does not change or add any functionality, it just uses a new API. It is part of the task to turn the lx6 control code instructions into a flat buffer, work ongoing. 
As we have no CI test for this part of the codebase at the moment, I have checked manually that the dumped instructions (module_matmul_static_dispatch_0_elf.insts.txt) in the example are unchanged. 
I also checked that it is safe to remove the cloning of the ModuleOp passed to generateIPUInstructions (mlir-aie does not mutate the ModuleOp).

Use new mlir-aie API (instructions as vector<uint32_t> 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
runtime/src/iree-amd-aie/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/native_executable.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc

Write the xclbin and lx6 instructions to a flatbuffer, which eventually ends up in the .vmfb artefact generated by the compiler. The design for the AIE backend here is based on the CUDA plugin's design. 
This needs further testing, once the ends are connected. I can see the xclbin and lx6 control code instructions are inserted into the MLIR module, and the .vmfb file is generated, but the ultimate test requires using the runtime. In other words the compilation and artefact generation seems fine:
```
./iree-compile -o test.vmfb --mlir-print-ir-after=iree-hal-serialize-executables ... 
```
but the ultimate test requires the runtime, which still has a few missing pieces on the command buffer side
```
./iree-run-module --device=xrt --module=../scripts/scripts_2/test.vmfb --input=8x16xi32 …
```

Flatbuffer executable serialization (xlcbin, lx6 instructions)

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
tests/samples/CMakeLists.txt
tests/samples/matmul_fill_spec_pad_new.mlir
tests/samples/tile_and_fuse.mlir

-- This commit adds the initial effort for tiling + fusing TileInterface ops using scf.forall by creating a new pass `--iree-amdaie-tile-and-fuse`.
-- It creates a new concise transform dialect script and adds a `--iree-amdaie-tile-and-fuse` test case to demo the generalised feature.
Co-authored-by: Nirvedh Meshram <nmeshram@amd.com>
Co-authored-by: Abhishek Varma <abhvarma@amd.com>

[AMD-AIE] Add a pass to tile and fuse TileInterface ops using scf.forall

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPadAndBufferize.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Cleanup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
tests/samples/CMakeLists.txt
tests/samples/matmul_fill_spec_pad_new.mlir
tests/samples/matmul_fill_static_i32.mlir
tests/samples/pad_and_bufferize.mlir

-- This commit introduces a pass which would pad a MatmulOp, for now, and would rewrite/transform its input operands for 1st level.
-- It also introduces a clean up pass.

[AMD-AIE] Add initial transform and padding strategy for Matmul + cleanup

---

runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/direct_allocator.cc
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.h
runtime/src/iree-amd-aie/driver/xrt/native_executable.cc
runtime/src/iree-amd-aie/driver/xrt/pipeline_layout.cc
runtime/src/iree-amd-aie/driver/xrt/pipeline_layout.h
runtime/src/iree-amd-aie/driver/xrt/xrt_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_buffer.h
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc

This PR adds the changes in the following
1. buffer/allocator to use pointers of XRT objects in IREE C structs
2. changes needed in the native executable to correctly load it
3. initial command buffer
It was also noticed that the `buffer_flush_range` and `buffer_invalidate_range` were not being called so we synchronize the buffers in the dispatch as they are not cache coherent between device and host.
This was tested by using the following run command for a simple matmul
```
iree-run-module --device=xrt --module=../test.vmfb  --input=8x16xi32=2 --input=16x8xi32=6
EXEC @matmul_static
result[0]: hal.buffer_view
8x8xi32=[192 192 192 192 192 192 192 192][192 192 192 192 192 192 192 192][192 192 192 192 192 192 192 192][192 192 192 192 192 192 192 192][192 192 192 192 192 192 192 192][192 192 …
```

Implement command buffer and fix buffer/executable issues

---

runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt

The XRT runtime driver was missing a cmake library dependency after the IREE update.

Fix XRT runtime driver

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerWorkgroupCount.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPadAndBufferize.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Cleanup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_workgroup_count.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level2.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pad_and_bufferize.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir

Most of the passes added recently dont need to run on the
`hal.executable.variant`. They could be run on `func.func`. This
removes a lot of boiler plate from the tests. As a consequence the
workgroup count region handling needs to be moved out of the tile and
fuse pass since it has to be run in a pass rooted on a
`hal.executable.variant`. Move just the workgroup count handling to a
separate pass.
Also organize passes better in header and tablegen files (make them
alphabetical).

NFC: General cleanup of IREE-AMD-AIE code and tests.

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPadAndBufferize.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pad_and_bufferize.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir
tests/samples/CMakeLists.txt
tests/samples/matmul_fill_static_i32.mlir
tests/samples/matmul_fill_static_i32_config.mlir

This PR consists of two commits :-
**Commit 1 (Create TranslationInfo and LoweringConfig):**
-- This commit adds tile sizes and pass pipelines via lowering_config
and translation_info respectively.
-- This is the initial effort towards generalizing the AIE codegen
pipeline. Currently setting tile sizes suiting the Matmul pad based
approach.
Signed-off-by: Nirvedh Meshram <nmeshram@amd.com>
**Commit 2 (Use TranslationInfo and LoweringConfig):**
-- This commit adapts the codegen flow to use lowering_config and
translation_info.
-- This basically involves :-
a. Adapting `--iree-amdaie-tile-and-fuse` to use lowering_config
in order to fetch the tile size for a particular tiling level.
b. Segregate the AMDAIE codegen flow to have two separate pipelines:
i. Transform dialect pipeline ii. Multi …

[AMD-AIE] Add amenities for setting and using TranslationInfo and LoweringConfig

---

runtime/src/iree-amd-aie/driver/xrt/native_executable.cc

The AIE device is not cache coherent, so the IPU instructions need to be flushed explicitly.

Sync the IPU instruction sequence before execution

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pack.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pad.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pad_last.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pad.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir

-- This commit adds AMDAIEMemSpace EnumAttr to mark memorySpace
during `--iree-amdaie-bufferize-to-alloc`.

[AMD-AIE] Create and use AMDAIEMemSpace EnumAttr to mark memorySpace

---

compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp

Target AIRTransformOps uses symbols in AIRTransformPasses, there would be a circular dependency but AIRTransformPasses doesn't actually need AIRTransformOps.

Fix build dependencies & unused variable warning

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level2.mlir

-- This commit prefetches the lowering config before applying
packing operation and then sets the same to the final packed op.
This solves the [Transient failure of pack_pipeline_e2e.mlir](https://github.com/nod-ai/iree-amd-aie/issues/118) - the `lowering_config` was not carried forward after the first application of `pack-and-transpose` and due to cascading effect `tile-and-fuse` couldn't perform tiling from 2nd level onwards.

[AMD-AIE] Prefetch lowering config before Packing and set later

---

.gitignore
build_tools/ci/run_matmul_test.sh
tests/matmul/generate_e2e_matmul_tests.py

This can be used to enable a matmul test while the CMake way of doing this catches up.

Add scripts for e2e Matmul CI

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
tests/samples/CMakeLists.txt
tests/samples/pack_pipeline_funcIR_2core.mlir
tests/samples/pack_pipeline_funcIR_4core.mlir

The PackPipeline makes only use of one AIE tile so far, by tiling to `(16,64)` at the first tiling operation.
With the new flag `iree-amdaie-num-cores` this behaviour can be adapted, namely
- `iree-amdaie-num-cores=2`: tile to `(16,128)` and use two AIE tiles
- `iree-amdaie-num-cores=4`: tile to `(16,256)` and use four AIE tiles.
By default, a single tile is used. Values different than 1, 2 or 4 result in an error.
Note that this PR is built on top of https://github.com/nod-ai/iree-amd-aie/pull/127, assuming that this will soon be merged.
This flag is ignored within the PadPipeline and SimplePackPipeline.

Add multicore flag

---

.github/workflows/ci.yml
build_tools/ci/pad_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

This gives the deployed xclbins a unique name based on the current workflow run. This avoids a potential collision where parallel jobs could overwrite the deployed kernel of another job, thereby un-deploying it. Then, a cleanup step that runs even if the job is cancelled erases any kernels that were deployed using the unique name scheme.

Ensure cleanup and avoid conflict between jobs

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level2.mlir

This PR involves :-
1. Creating AMDAIEDialect.
2. Creating AMDAIEEnum/Attributes.
3. Creating PackingConfig Attribute infra.
4. Adapting KernelDispatch to set packing_config attribute.
5. Adapting --iree-amdaie-pack-and-transpose to work with the packing_config attribute set earlier.
5. Refactoring the directory structure to make maintaining codebase "easier" and aligns with the restructuring upstream.

[AMD-AIE] Add AMDAIEDialect/Attributes + PackingConfig + Update KernelDispatch/pack-and-transpose

---

tests/OPT/failing_tests/CMakeLists.txt
tests/OPT/failing_tests/gemm_f32.mlir
tests/OPT/failing_tests/gemm_i32.mlir

-- 2 of the 5 tests were wrong/invalid - this commit rectifies that.
-- It also adds the corresponding f32 counterpart to completely cover
all GEMMs seen in the OPT dispatches.
GEMM of OPT has three blockers :-
1. Op support. (a `linalg.generic` that performs matmul transpose AND a `linalg.batch_matmul`)
2. Shape support.
3. Element type support (`f32`).
My intention was to keep a self-contained GEMM check particularly for OPT but the previous test only satisfied `2`.
So while trying to add others, I bumped into errors in SSA access in the test case which wasn't caught due to `XFAIL`. Since this mistake from my end would've caused a red-herring later, I'm rectifying the same in this PR.
I've verified both the files now : `iree-opt …

[AMD-AIE] Update GEMM OPT tests

---

.github/workflows/ci.yml
build_tools/ci/pad_test.sh
build_tools/ci/run_matmul_test.sh
tests/matmul/generate_e2e_matmul_tests.py
tests/matmul/requirements.txt

These tests are compared against a reference matmul implementation with pseudo random initialization. The test sizes are currently limited. In upstream IREE similar tests are build using cmake and run using ctest, however that is currently not possible for a plugin so the script added here is an alternate way of doing it.

Add initial E2E correctness tests

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

Fix for https://github.com/nod-ai/iree-amd-aie/issues/177
1. Added subdirs for each parallel executable, so that their commonly named files don't step on each other
2. Fixed a use-after-free bug that caused the aie2xclbin command line to have garbage in it

added subdirs for executables, fixed use after free

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
tests/samples/simple_pack_pipeline_e2e.mlir

-- This commit adds initial effort for enabling matmul transpose.
-- Matmul transpose is represented via a linalg.generic op with the
transpose materializing as the interchange of the dimension. This
commit therefore adds the initial infra for dealing with linalg.generic
and caters specifically to the transpose case.
NOTE: The `--split-input-file` doesn't seem to work for some reason - should be a trivial fix - I'll look into it, but rest of the infra is going to be as it is.

[AMD-AIE] Add initial effort for enabling matmul transpose

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

-- This commit adds various updates to `--iree-amdaie-lower-to-ukernel`
pass.
-- The updates made are as follows :-
a. Target Simple-Pack pipeline.
b. Add fn_def to the generated iree_codegen.ukernel op.
c. Add a pass option `path-to-ukernels` to help add the same to the fn_def as mentioned in point b.

[AMD-AIE] Update lower-to-ukernel pass

---

build_tools/ci/run_matmul_test.sh

1) Allow all paths (peano, vitis, mlir-aie) configurable by user 
2) Do not attempt to 'sign' xclbins unless a script for signing is present

Make matmul test script easy to run outside of CI

---

tests/samples/CMakeLists.txt

This was just a POC transform dialect script being tested, so no concern here of a bug somewhere important being ignored.

Disable conv2d test

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/PassDetail.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_dma.mlir

This pass adds simplifying canonicalizations that we expect to be legalized into aie dma operations using subsequent passes.

Add air.dma_memcpy_nd canonicalization pass

---

.github/workflows/ci.yml
build_tools/ci/print_ir_aie2xclbin/linalg_matmul_f32.mlir
build_tools/ci/print_ir_aie2xclbin/print_ir_aie2xclbin.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h

Can now use 
`iree-compile --aie2xclbin-print-ir-after-all ...`
etc. to print mlir-aie pass information (pipes to stderr or stdout, whichever mlir pipes to by default). 
I should add a test for this. 
4 flags:  
print ir before/after all
print ir module scope
disable threading.

Flags to print IR in mlir-aie passes (i.e. in aie2xclbin)

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
tests/samples/simple_pack_pipeline_e2e.mlir

This is in preparation for changing the lowering flow without the maintenance burden of supporting it for non-default pipelines.

Make pad-pack as the default pipeline and decouple its lowering from other pipelines

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

New features in MLIR-AIR:
- Updates in `air-collapse-herd` to unblock development for the new multi-memtile buffer allocator.

Update mlir-air submodule

---

compiler/plugins/target/XDNA-OPLIB/CMakeLists.txt
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/CMakeLists.txt
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/CMakeLists.txt
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/PassDetail.h
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/Passes.cpp
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/Passes.h
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/Passes.td
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/Transforms/XDNAOPLIBHelloWorld.cpp
compiler/plugins/target/XDNA-OPLIB/xdna-oplib/XDNAOplibRegistration.cpp
iree_compiler_plugin.cmake
tests/samples/CMakeLists.txt
tests/samples/xdna_oplib_plugin.mlir

This adds a new XDNA OpLIB plugin in the repo. This plugin has to be explicitly activated using `--iree-plugin=xdna-oplib`.

Add a new XDNA-OpLIB plugin.

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp

This PR tries to first pack to improve the chances of getting the desired pack and then chooses the inner k tile based on the resulting untiled size.

Change tiling/packing order to be more vectorization friendly

---

experimental/delegate/mlp_aie_bf16_plugin.cpp

I had left a plain text comment with no leading comment token in an #if 0 section.  It appears that g++ parses the section regardless!  The fix is to add the comment token.

Fix for g++ not liking plain text in an #if 0

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy.mlir

-- This commit generalizes tiling/packing config based on a given
element type.
-- The rationale behind this is that element type with lesser memory
footprint can exploit higher tiling/packing sizes and vice versa.

[AMD-AIE] Generalize tiling/packing based on a given element type

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/peel_for_loop.mlir

This PR adds support to peel the last iteration out of the scf.for loop. This functionality is a special case of [peelForLoop](https://github.com/llvm/llvm-project/blob/556fe5f290ea88dcbb7ced16b0f057dcebce1fd0/mlir/lib/Dialect/SCF/Transforms/LoopSpecialization.cpp#L119) in llvm-project. However, there is a hard constraint in the upstream function that peeling only works if the step size doesn't divide the upper bound evenly. In our application, we'll need a function to peel the last iteration off in all situations. To not break the upstream patterns for loop peeling, a special function is added in this repository.

Add support to peel the last iteration of the for loop

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/peel_for_loop.mlir

This PR fixes the bug in the previous PR https://github.com/nod-ai/iree-amd-aie/pull/243, so that it works when (%ub - %lb) mod (%step) == 0.

Fix affine map for peeling the last iteration

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
tests/matmul/generate_e2e_matmul_tests.py

Will also require this small change in aie: https://github.com/Xilinx/mlir-aie/pull/1149
I've verified that with these changes, I can add a test to our matmul script. 
Is there anywhere else we assume element types are >= 16 bits? Please let me know if so.

Changes to get matmul with i8 operands (and i32 result) e2e working

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
experimental/delegate/CMakeLists.txt
iree_runtime_plugin.cmake
runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/native_executable.cc

Removed the code to amend the library search path, since libcdo_driver is now bundled with mlir-aie. Vitis path is only configured when using chess. Fixed some CMake issues finding the boost headers on Windows. Propogate C++ exceptions as IREE status when loading the xclbin file.

Fix windows build

---

experimental/delegate/CMakeLists.txt
experimental/delegate/linalg.pdl.mlir
experimental/delegate/mlp.mlir

PDL matching has compile time performance benefit over transform dialect matching for large models. Here we are doing the matching a linalg level, mostly following what happened at the torch level in the upstream IREE matcher test. I was able to run the resulting IR through iree-compile and was able to delegate the matmul to AIE device with iree-run-module.

[DELEGATE] Add a PDL matcher to match a linalg.matmul

---

tests/transform_dialect/CMakeLists.txt
tests/transform_dialect/matmul_fill_spec_pack_funcIR.mlir
tests/transform_dialect/matmul_fill_spec_pack_peel.mlir

- Rename previous script `matmul_fill_spec_pack_peel.mlir` for funcIR prototype to `matmul_fill_spec_pack_funcIR.mlir`. 
- The latest `matmul_fill_spec_pack_peel.mlir` implements `forall-for-forall-for` structure with peel operation for the first iteration. Both levels of packing happen under the outer forall op, and are gradually fused into the inner loops.
- With this method, it avoids data movement across memory hierarchy between the peeled and the remaining loops. However, it results in a larger memory allocation for the results in L1. 
- Tested with input sizes not multiple of tile sizes, and it works with [upstream hack](https://github.com/llvm/llvm-project/commit/88ae64dcd4c49542133303a007ff01ec6ae2f548). The generated IR can be found …

Add latest transform dialect for pack-peel based method

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPad.cpp
tests/matmul/generate_e2e_matmul_tests.py

@nirvedhmeshram I've been wanting to try this for a while, and your comment in the standup this morning made me just do it. 
If I understood correctly (sorry I was having audio issues) when you compile 2+ matmuls together, you hit runtime issues? 
This PR does:
1) removes the groups 'large' 'small' 'legacy_*' and now a test must be specified directly with m,n,k values. 
2) some minor superficial changes.

Make matmul tests take m,n,k directly 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFusePackIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_pack_into_loop.mlir

This PR fixes the problem that the user of loop block argument is not linalg.generic. This PR is needed for pack-peel based pipeline.

Fix FusePackIntoLoop pass

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

-- This commit updates `--iree-amdaie-lower-to-ukernel` pass to deal
with optional ExtFOps in order to match body of a linalg.generic
matmul.
-- Lit tests to demo the following were added :-
a. bf16 inputs/output.
b. bf16 inputs - f32 output.

[AMD-AIE] Update lower-to-ukernel pass to deal with ExtFOps

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/propagate_data_layout.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir

- Add data layout propagation in the pack-peel pipeline, so the pack ops can be propagated for elementwise ops.
- Modify the tileAndFusePass to include an option to not tile the elementwise ops.
- After these changes the generated IR before fusion is as https://gist.github.com/yzhang93/2d83d40f4cec20f58a135af73209759e
- TODOs:
1) Modify bufferizeToAllocation pass to include memory promotion for elementwise ops.
2) Add a method to automatically detect matmul-elementwise vs matmul-only dispatches, so that we can set different peel options. For matmul-only dispatch just the first iteration needs to be peeled, while for matmul-elementwise dispatch both the first and the last iterations need to be peeled.

Changes to pack-peel pipeline for matmul-elementwise ops fusion

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir

- We will need to run this pass for elementwise ops after the elementwise op is fused into the last iteration of the matmul computation.

Add support to bufferize the operands from elementwise ops

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/peel_for_loop.mlir

- In pack-peel pipeline, for matmul dispatch only the first iteration is peeled from the scf.for, while for matmul-elementwise dispatch, both the first and the last iterations need to be peeled. To avoid bringing extra flags to switch between such cases, the  default option `peelingType` is overwritten as `FirstLast` when it detects the matmul-elementwise pattern. 
- Clean up the pass option names as suggested in the previous review comment https://github.com/nod-ai/iree-amd-aie/pull/275#discussion_r1569154836.

Overwrite option to force peeling first and last iterations for matmul-elementwise fusion

---

build_tools/ci/run_matmul_test.sh

New bugfix:
- Improve AIRRtToIpu pass stability when any wrap size exceeds 1023.
- The pass attempts to tile the wrap dimension using one extra wrap-and-stride dimension, taking the original wrap's largest integer factor (less than 1024) as the wrap's tiling factor (previously hardcoded as 512).
- Fixes error 1 in https://github.com/nod-ai/iree-amd-aie/issues/285.

Bump mlir-air; add a small CI test to exercise the new airrt-to-ipu feature

---

build_tools/ci/run_matmul_test.sh

Bugfix in MLIR-AIR:
- Fixup an issue with aie.core lock allocation, which mistakenly lowers peeled code as ping-pong buffered code, leading to numerical error.

Bump mlir-air; add initial ci test for pack-peel pipeline

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp

This makes sure we make a reasonable tiling/packing config for any shape that is a multiple of the minimum packing config.
The order is 
1. Set the packing config first.
2. Then the inner tile which should be a multiple of the packing.
3. Then the outer tile that should be a multiple of the inner tile.

Do packing before tiling in pad-pack pipeline

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h

This PR removes 2 things:
1)  The method `addMLIRAIRAIELegacyLoweringPasses` which is not needed it seems (pad-pack uses 
the very similar `addMLIRAIRAIELoweringPasses` and pack-peel uses neither (is this an oversight?)). 
2) ` static PassPipelineRegistration<> AIELoweringPipeline("iree-amdaie-aie-lowering-pipeline", ... ` which doesn't seem to be used anywhere. 
Is it ok to just go ahead with these removals, or is a plan to use them in the future?

Remove legacy pipeline

---

.github/workflows/ci.yml

Bump mlir-air to latest xilinx/main   4b0b5b3a63e2a71d51d76651b3692a43c96d57e7
Bump mlir-aie to mlir-aie's pinned hash e5866f4f360659dbc93d6a97bac0fd2a12672189

Bump mlir-aie and mlir-air

---

.github/workflows/ci.yml
build_tools/ci/print_ir_aie2xclbin/print_ir_aie2xclbin.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h

- This is useful to locate slow passes in mlir-aie (I used it to find the slow pass for https://github.com/Xilinx/mlir-aie/pull/1431)
- Required bump of mlir-aie wheel used

MLIR --timing flag to aie2xclbin passes

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFusePackIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Cleanup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir
tests/samples/CMakeLists.txt
tests/samples/pack_peel_pipeline.mlir
tests/samples/pack_peel_pipeline_matmul.mlir
tests/samples/pack_peel_pipeline_matmul_elementwise.mlir

- Integrate FuseConsumerIntoLoopPass to pack-peel packline. Adjust the order of certain passes to avoid bufferization problem.
- Modified BufferizeToAllocationPass and FusePackIntoLoopPass to generate correct IR without extra alloc/copies after bufferization.
- Add an e2e matmul-elementwise example to demonstrate the lowering through AIR and generate NPU instructions.

Integrate FuseConsumerIntoLoop to pack-peel pipeline and fix bufferization

---

experimental/delegate/.gitignore
experimental/delegate/CMakeLists.txt
experimental/delegate/README.md
experimental/delegate/kernels/CMakeLists.txt
experimental/delegate/matmul.mlir
experimental/delegate/mlp_aie_bf16_plugin.cpp
experimental/delegate/opt.mlir
experimental/delegate/opt.pdl.mlir

Added several enhancements to AIE delegates:
- Now using a 4x4 vector matmul of shape 8x768x768, stored in Azure
- dtypes of model and AIE kernel inputs and outputs now defined in one place
- All tensor conversion and copying code templatized to automate those functions and use minimal implementations when possible
- New PDL transform to convert 8x768x768 matmul in linalg MLIR to external func call
- prototype code for direct XRT buffer use (disabled until HAL buffers are allocated with XRT)
- copy from result buffer to kernel now switchable by macro (not needed for both kernels we're currently using)

[Delegate] Enhancements in support of OPT matmul

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_failures.mlir

This is a non-functional change tothe lowering strategy code. It just 
1) makes the error clearer when the tensor size does not divide the AIE instruction size
2) refactors the functions for obtaining packing sizes to be slightly clearer
3) avoids non-const ref vectors in APIs where vectors could be const 
4) small style changes 
I would like to follow it up with a small change to improve stategy to avoid using just 2 rows of 4x4 array.

Lowering strategy code and diagnostics improvements 

---

experimental/delegate/CMakeLists.txt
experimental/delegate/README.md
experimental/delegate/large-matmul-f32.mlir
experimental/delegate/large-matmul-f32.pdl.mlir
experimental/delegate/mlp_aie_bf16_plugin.cpp

By default, the delegate now expects f32 inputs instead of bf16.
For the Large Matmul case, there are now two PDLs for rewriting to call the delegate, one that matches bf16 inputs (large-matmul.pdl.mlir) and one that matches f32 inputs (large-matmul-f32.pdl.mlir).

[Delegate] Converted delegate to expect f32 inputs

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt

The following error when building was reported
```
.../iree-amd-aie/compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp:28:10: fatal error: 'runtime/plugins/AMD-AIE/iree-amd-aie/schemas/xrt_executable_def_builder.h' file not found
28 | #include "runtime/plugins/AMD-AIE/iree-amd-aie/schemas/xrt_executable_def_builder.h"
```
Adding this deps should fix that.

add missing deps in compiler target

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

New feature in MLIR-AIR:
- Added logic in `MemrefShrinkage` pattern (part of `AIRSegmentLoopFusion` pass) to support vectorized kernel code.

Enable vectorization passes in pack-peel pipeline

---

.github/workflows/ci.yml
build_tools/ci/run_matmul_test.sh

Adds line
```
sudo prlimit -lunlimited --pid $$
```
to .github/workflows/ci.yml
Proof that this works:
Fails: https://github.com/nod-ai/iree-amd-aie/pull/332
Passes: https://github.com/nod-ai/iree-amd-aie/pull/330

Workaround for CI host memory limit

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy.mlir
tests/samples/pack_peel_pipeline_matmul.mlir

- This PR modified the tiling and packing parameter settings for pack-peel pipeline following the existing strategy for pad-pack pipeline. These changes are specially made to make challenging matmul input sizes compiling and running on the device. The performance is not the main concern at this time.
- Bump MLIR-AIR to include several fixes in AIR.
- With this PR 7/8 matmul tests added here https://github.com/nod-ai/iree-amd-aie/pull/334 have passed using pack-peel pipeline. The remaining one failed at AIE level. @erwei-xilinx will help take a further look.

Modify the config settings for pack-peel pipeline

---

experimental/delegate/CMakeLists.txt
experimental/delegate/large-matmul-f32.mlir
experimental/delegate/matmul-elementwise-f32.mlir
experimental/delegate/mlp_spec_matmul.mlir
experimental/delegate/mlp_spec_matmul_elementwise.mlir

The matmul test shows parity with the PDL test and runs with correct numbers e2e in local testing.
The matmul+elemetwise test generates the expected dispatch and compiles. The numerics of these are not tested as there is no delegate (cpu or AIE) for this. 
The tests use iree-compile because there is an unrelated crash in using iree-opt.

[Delegate] Add transform dialect scripts for matmul+elementwise

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertLoopsForVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_loops_for_vectorization.mlir

With the current pipeline, matmul_tranpose_b ops are converted to matmul-like generics here: https://github.com/nod-ai/iree-amd-aie/blob/784dedb18b9768ebfff7b344906ee9052e8674eb/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp#L121 (this is for the pad-pack pipeline, not sure how peel-pack pipeline differs). As a result, by the time the vectorization pass runs, there are no matmul_transpose_b operations (or equivalent linalg.generics) in the IR. 
I would to change this (in a future PR). Specifically I would like to change inner permutation of packing (see https://github.com/nod-ai/iree-amd-aie/blob/784dedb18b9768ebfff7b344906ee9052e8674eb/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp#L134) to have no permutation. This will …

Make loops-for-vectorization recognize matmul_transpose_b

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

-- This commit updates `--iree-amdaie-lower-to-ukernel` pass by
adding zero filling ukernel matcher for a linalg.fill op.

[AMD-AIE] Lower zero filling linalg.fill to ukernel

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td

Just adding some more documentation to the `DoublyStridedOpInterface` as I noticed a major method to be implemented was missing.

Update DoublyStridedOpInterface doc with createDoublyStridedOp method

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy.mlir

This is low priority as pad-pack isn't going to be our main pipeline, and this doesn't fix any hangs since https://github.com/Xilinx/mlir-air/pull/562/ landed,  but maybe a nice thing to have (we can use in peel-pack later).
The pad-pack pipeline currently targets a 4x4 AIE array, so for a fixed shared memory tiling in the M- and N- directions (M0 and N0) it is better to have 
```
M1=M0/4, N1 = N0/4
```
than 
```
M1=M0/2, N1 = N0/2
```
where M1 and N1 are the tiling sizes on the AIE core memory. 
This PR checks for M0/M1 = 2 and if possible halves M1 so that M0/M1 = 4 (ditto the N- dimension) 
Note that since https://github.com/Xilinx/mlir-air/pull/562/files has landed this change is purely for performance and not for correctness.

For the pad-pack pipeline, avoid tile size ratio of 2

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPropagateDataLayout.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/propagate_data_layout.mlir
tests/samples/pack_peel_pipeline_matmul_elementwise.mlir

- Add [upstream support](https://github.com/shark-infra/llvm-project/blob/f2d824e381755993b6e8c32f4de89192189ca9a7/mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp#L1864) locally to remove output dependency, since the pattern is not exposed and cannot be called directly. This pattern is added in `AMDAIEPropagateDataLayoutPass`, so that whenever we do data layout propagation it will get the desirable output for matmul-elementwise fusion. @MaheshRavishankar please let me know if it is reasonable to add it here, otherwise I'm open to move it into a separate pass or add the pattern to the cleanup pass.
- Currently, tests without vectorization compile through, but crash at `AIRToAIESchedulingUtilsPass` with vectorization. @erwei-xilinx

Remove redundant data copy of elementwise op

---

experimental/delegate/CMakeLists.txt
experimental/delegate/kernels/CMakeLists.txt
experimental/delegate/matmul-16k.mlir
experimental/delegate/matmul-16k.pdl.mlir
experimental/delegate/mlp_aie_bf16_plugin.cpp

Several enhancements in support of a 16384x16384x512 matmul with bf16 inputs and f32 outputs:
- New PDL for 16k matmul
- timers added for NPU setup and kernel execution
- cleanup of delegate tracing for better code readability
- re-indentation of some functions for consistency
- kernel (on Azure) generated via AIE direct codegen

[Delegate] Support for 16k matmul

---

tools/plugins/CMakeLists.txt

When attempting to bump IREE (or use a branch off a more rencent IREE than we have) I see some linker errors of the form 
```
ld.lld: error: undefined symbol: mlir::iree_compiler::IREE::LinalgExt::AttentionOp::getLoopIteratorTypes()
>>> referenced by TilingInterface.h.inc:292 (llvm-project/tools/mlir/include/mlir/Interfaces/TilingInterface.h.inc:292)
>>>               ../compiler/src/iree/compiler/Dialect/LinalgExt/IR/CMakeFiles/iree_compiler_Dialect_LinalgExt_IR_IR.objects.dir/LinalgExtDialect.cpp.o:(mlir::detail::TilingInterfaceInterfaceTraits::Model<mlir::iree_compiler::IREE::LinalgExt::AttentionOp>::getLoopIteratorTypes(mlir::detail::TilingInterfaceInterfaceTraits::Concept const*, mlir::Operation*)) in archive lib/libiree_compiler_Dialect_LinalgExt_IR_IR.a
```
This PR fixes these …

Fix linker error seen when using different IREE branch

---

.github/workflows/ci.yml
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_to_air.mlir
sync_deps.py
tests/transform_dialect/conv_fill_spec_pad.mlir
tests/transform_dialect/matmul_fill_spec_pack_funcIR.mlir
tests/transform_dialect/matmul_fill_spec_pack_peel.mlir
tests/transform_dialect/matmul_fill_spec_pad.mlir
tests/transform_dialect/matmul_fill_spec_pad_pack.mlir
tests/transform_dialect/matmul_fill_spec_pad_pack_peel.mlir
tests/transform_dialect/matmul_fill_spec_simple_pack.mlir

All bumped to what is currently the most recent version available 
lit test updates for: 
https://github.com/llvm/llvm-project/pull/90897/files and
https://github.com/llvm/llvm-project/pull/90040

Bump IREE, mlir-aie, mlir-air, mlir-aie wheel 

---

experimental/delegate/kernels/CMakeLists.txt
experimental/delegate/matmul-16k.mlir
experimental/delegate/matmul-16k.pdl.mlir
experimental/delegate/mlp_aie_bf16_plugin.cpp

Support for running 2 different AIE matmul kernels in one model.
- PDL now replaces matmuls for both 16384x16384x512 and 16384x512x16384 (MxNxK)
- delegate now uses M, N, and K from HAL to determine which matmul kernel to use instead of having shapes hard-coded
- If the MRU kernel is not the same shape as the requested matmul, the right xclbin/instructions are loaded before doing the matmul
- New kernel for 16384x512x16384 checked in to Azure

[Delegate] Dual xclbin support

---

compiler/plugins/target/AMD-AIE/Translation/AIESerializer.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUnrollAndDistributeWorkgroup.cpp

Fix deprecated `.cast<U>` and `.dyn_cast<U>` warnings. Use `mlir::cast<U>()` and `mlir::dyn_cast<U>()` instead.

Fix deprecated cast warnings

---

experimental/delegate/kernels/CMakeLists.txt
experimental/delegate/mlp_aie_bf16_plugin.cpp

- new kernels for Strix
- fixed typo in Phoenix kernel name (Azure now has both versions, typo and post-typo)
- changed macro `ENABLE_KERNEL_RUN` to the more understandable `DRY_RUN` and flipped sense (+ve to -ve)
- leaving on tracing for now for better visibility on Strix

[Delegate] Added support for Strix

---

tests/samples/CMakeLists.txt
tests/samples/matmul_peeled_objectfifo.mlir

Example of peeled matmul lowering to AIE objectfifo. This can be temporary until the pipeline is set up and an e2e example can be created. In the meantime, this will ensure that the initial example stays functional.

Add peeled matmul to objectfifo sample

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level2.mlir

This PR changes inner permutation of pack operation to keep the original form of matmul A(m,k) x B(k, n) and matmul_transpose_b A(m, k) x B(n, k).

Modify the pack-transpose config for matmul_transpose_b

---

sync_deps.py

Previous PR accidentally pointed to iree main.  This PR points to the latest iree branch shared/tresleches-cpu, which includes performance improvements for the CPU target.

Bump iree to latest shared/tresleches-cpu

---

.github/workflows/ci.yml

- Attempt to add merge trains / merge queues / merge groups to CI. 
- The goal of this PR is to free developers from having to "Update branch" if a patch lands between them submitting a PR and CI passing: 
- Nice description of how they work (gitlab equivalent): https://about.gitlab.com/blog/2020/01/30/all-aboard-merge-trains/#what-are-merge-trains-and-how-do-they-help%3F
- Based on PR from @stephenneuendorffer in mlir-aie: https://github.com/Xilinx/mlir-aie/pull/1461

[CI] Use merge groups 

---

experimental/delegate/kernels/CMakeLists.txt
experimental/delegate/mlp_aie_bf16_plugin.cpp

v1 kernels had numerics issues.  The new v2 kernels, being 4x4 instead of 8x4, are a tad slower but produce more accurate results.

[Delegate] Use v2 strix kernels

---

compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt

Update MLIR-AIE to include aievec changes to fix matmul_transpose_b tests. Will need to update the wheel once it has a release to include the latest PR https://github.com/Xilinx/mlir-aie/commit/6f70bfe4904ec719042d7ebd8ded9ad8b31bb5b6.

Bump MLIR-AIE

---

.github/workflows/ci.yml
build_tools/ci/run_matmul_test.sh

The latest mlir-aie wheel fixes the matmul_transpose_b ci test.

Update mlir-aie wheel and matmul_transpose_b ci test

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/peel_for_loop.mlir
tests/samples/pack_peel_pipeline_matmul_elementwise.mlir

- With this work https://github.com/nod-ai/iree-amd-aie/pull/351, we change the pack-peel pipeline to always peel the first and the last iteration and fuse the unpack op into the inner forall loop for matmul only and matmul-elementwise dispatch.
- With this change, we have made progress on codegen for matmul-transpose-b and matmul-elementwise example dispatches to a reasonable state.
- A minor issue is with [upstream change](https://github.com/llvm/llvm-project/pull/90189), there is redundant data allocation and copy after bufferization ([example IR](https://gist.github.com/yzhang93/55f448368db32cccd2af31c730cc878a#file-gistfile1-txt-L342)). So currently I have to disable the canonicalization pass [here](https://github.com/nod-ai/iree-amd-aie/pull/392/files#diff-42f0d0bb098689f25ee68e8f05e …

Update pack-peel pipeline and ci tests

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir

-- This commit adds a fix to DmaCpyNd -> Circular/Npu DmaCpyNd.
-- If the source of DmaCpyNd op is from L3 then the addressing will be
controlled by the uController.
-- If the target of DmaCpyNd op is from L3 - then addressing will be
controlled by the circular DMA at shim tile.

[AMD-AIE] Fix the onus of controlling addressing for L3 DmaCpyNdOp

---

.github/CODEOWNERS

Adding myself to the CODEOWNERS file for compiler to automatically get notifications and requests for review on PRs.

Add jtuyls to compiler in CODEOWNERS file

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackToDma.cpp

I don't know why but the current form of the walk in this pass generates the following error on M1 Mac:
```
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  iree-opt                 0x000000010de3e880 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  iree-opt                 0x000000010de3ca34 llvm::sys::RunSignalHandlers() + 112
2  iree-opt                 0x000000010de3ef2c SignalHandler(int) + 344
3  libsystem_platform.dylib 0x0000000199fc7584 _sigtramp + 56
4  iree-opt                 0x0000000108758228 mlir::TypeID::operator!=(mlir::TypeID const&) const + 32
5  iree-opt                 0x00000001087581f8 mlir::OperationName::Impl::isRegistered() const + 48
6  iree-opt …
```

Fix AMDAIEPackToDma.cpp on Mac

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir

-- This commit makes changes to the `iree-amdaie-create-aie-workgroup` pass.
-- Adds a few refactoring.
-- While building the workgroup of a function we would be cloning an operation to :-
1. Workgroup body.
2. Controlcode.
3. Core op (To be implemented).
-- Each of these cloning would be dependent on the respective IRMapper.
Specifically we would be checking if the IRMapper has the necessary operand values to perform a successful clone.
Co-authored-by: Jorn Tuyls <jorn.tuyls@amd.com>
Co-authored-by: Abhishek Varma <abhvarma@amd.com>

[AMD-AIE] Refactor + clone most of the operations based on IRMapper

---

.github/workflows/ci.yml
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/native_executable.cc

This PR makes the required changes to switch to executing kernels with transaction binary flow with no control packets. This is done by simply updating the mlir-aie wheel to latest so that this PR is contained in it,
https://github.com/Xilinx/mlir-aie/pull/1517

Bump mlir-aie wheel to switch to transaction binary flow

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute-cores-and-objectfifos.mlir

Add `DistributeCoresAndObjectFifos` changes for cpp pipeline and e2e example, see all changes here: https://github.com/nod-ai/iree-amd-aie/compare/jornt_cpp_pipeline?expand=1#diff-888fdafbbd093dc98e4fae55a26e7fa56065fc7506fedc0107b8a897c19f816a
- Add local memory distribution: rewrite a larger memory across multiple cores into dedicated ones for each core
- Add shared memory distribution: allocate different memories for logical objectFifos on the same shared memory tile to ensure different buffers will be used
- Rewrite L1 tile assignment to use new `amdaie.logicalobjectfifo.access` operations
- Rewrite L2/L3 tile assignment into two parts: 1) finding all potential tiles and 2) selecting specific tiles
NOTE: In this PR, the `amdaie.logicalobjectfifo.access`  operation is not supported e2e …

[DistributeCoresAndObjectFifos] Add local and shared memory distribution and rewrite

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

I noticed that whenever the xclbin compilation process fails (say that iree is not able to find the binary), it just fails but it is hard to find the reason. 
This just makes sure that the error message is displayed as well.

Adding error message whenever the xclbin tool fails to produce xclbin

---

build_tools/ci/cpu_comparison/run_test.sh
build_tools/ci/cpu_comparison/test_files/three_matmuls.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

There was a bug where were appending LX6 instructions to an existing vector for subsequent entry points rather than making a new vector for each entry point. This change fixes that and hence fixes https://github.com/nod-ai/iree-amd-aie/issues/447 which was indeed a kernel time out due to bad artifacts.
Also adds a multi-dispatch e2e test to CI.

Fix bug in artifact creation of the LX6 instructions

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetBCF.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetCDODirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetLdScript.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetNPU.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargets.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

This PR is part of a stack of PRs that refactor the dependency on MLIR-AIE. See https://github.com/nod-ai/iree-amd-aie/issues/430 for more information.
This PR vendors all necessary target emission utils that we need (and none that we don't 😄). Namely `AIETargetBCF`, `AIETargetCDODirect`, `AIETargetLdScript`, and `AIETargetNPU`. Just as for the previous "vendoring" PR, it's not worth it to bikeshed the code yet because it'll be refactored in a subsequent PR (e.g., `AIETargetNPU` will disappear and be absorbed into `AIEDmaToNpu`).
@nirvedhmeshram @newling this is now ready for review.

Vendor all target emission utils (6/n)

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

Contains fixes for 2 related issues:
1. On local memory distribution, static offsets/strides/sizes were not propagated.
2. Fix for DMA operations still containing offsets after a larger local memref + subview has been distributed across different cores by replacing it with multiple smaller memrefs.

[DistributeCoresAndObjectFifos] Fix local memref DMA access pattern

---

compiler/plugins/target/AMD-AIE/aie/AIECreatePathFindFlows.cpp

I would've liked to add Werror to CI, but it wasn't obvious what the best/canonical way to do this is, so for now just fixing this warning.

Fix for extra qualification C++ compiler warning

---

.github/workflows/ci.yml
compiler/plugins/target/AMD-AIE/aie/AIEDmaToNpu.cpp
compiler/plugins/target/AMD-AIE/aie/test/aiert_insts.mlir
compiler/plugins/target/AMD-AIE/aie/test/dma_to_npu.mlir
compiler/plugins/target/AMD-AIE/aie/test/dma_to_npu_issue_token.mlir
compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeLoopUnroll.cpp
sync_deps.py

Changes in updated submodules that require adaptation in iree-amd-aie:
- `NpuWriteBdOp` lost its ddr_id argument
- AIRPipeline.cpp was removed
- `mlir::ceilDiv` and the rest of `mlir/Support/MathExtras.h` was removed in favor of the LLVM equivalents (https://github.com/llvm/llvm-project/pull/95087)

Bump iree, mlir-air, mlir-aie

---

compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
compiler/plugins/target/AMD-AIE/air/ConversionPasses.cpp
compiler/plugins/target/AMD-AIE/air/TransformPasses.cpp
sync_deps.py

Bump iree to 4294a5b
Bump mlir-air to 4559217
mlir-aie remains unchanged, as mlir-air's pin of mlir-aie is unchanged.
Submodule changes that required adaptation in iree-amd-aie:
- AIR DmaToChannel pass moved from Conversion to Transform

Bump iree, mlir-air

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertLoopsForVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_loops_for_vectorization.mlir

Vectorization in iree-amd-aie consists of 2 passes:
1) tile linalg.generic ops in all leading dimensions, so that batched matmuls, and matmuls which have been packed into high-dimesions with multiple reduction dimensions, get replaced by unbatched 'atomic' matmuls with scf.for loops
2) lower the 'atomic' matmuls to the vector dialect (vector.contract and other vector dialect casts/copies). 
Before this PR, pass 1 applied to all linalg.generics, irrespective of their element type. However, pass 2 only applies to linalg.generics for which the operand element types have hardware support on AIE for vectorization. All linalg.generics with other types, like matmuls with i32 operands and result, are not converted to the vector dialect, they are later unrolled in a pass, linalg-to-loop (or …

[vectorization] Apply tiling only if element types vectorizable

---

compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h

Let's pull the bandaid off and use only in-tree passes. My apologies @nirvedhmeshram for giving you the run-around last week just do throw it away :(
Note, after this PR we should be fixing/patching in-tree passes first and upstreaming (those fixes) second.

Use only in-tree AIE/AIEX passes

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.h

Noticed this remaining piece of logic which is handling `amdaie.workgroup` inside the `AMDAIECreateAIEWorkgroup` pass, but is not needed anymore after https://github.com/nod-ai/iree-amd-aie/pull/406 as there shouldn't be any `amdaie.workgroup` ops inside the IR before this pass.

[CreateAIEWorkgroup] Remove unused buildForWorkgroupOp function

---

.github/workflows/ci.yml
build_tools/ci/cpu_comparison/run_test.sh
build_tools/ci/print_ir_aie2xclbin/print_ir_aie2xclbin.sh
build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetDirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h
iree_runtime_plugin.cmake
runtime/src/iree-amd-aie/aie_runtime/CMakeLists.txt
runtime/src/iree-amd-aie/aie_runtime/NoOpXclBinSignature.cxx

This PR adds executable targets to our CMakes to build both `xclbinutil` and `bootgen`; previously these were fetched/gotten from a distro of `mlir-aie` and/or env. We already have these same submodules (`XRT` and `bootgen`) so the only thing we're really vendoring here is the CMake. The advantages of this are :
1. After this PR and a follow-up taking care of `me_basic.o` (once https://github.com/Xilinx/llvm-aie/pull/109 lands) we will no longer need a distro of `mlir-aie` (but obv still need the submodule for a little while longer);
* Also we will be able to run lit tests for xclbin generation (i.e., during the build test step in CI);
3. We eliminate one dependency on OpenSSL (within `XRT`'s xclbinutil);
4. We will eventually move to not shelling out to these utilities and just calling …

Vendor `bootgen` and `xclbinutil`

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetCDODirect.cpp
runtime/src/iree-amd-aie/aie_runtime/CMakeLists.txt
runtime/src/iree-amd-aie/aie_runtime/test/utest.cxx

I goofed and didn't notice `aie-rt` had a device model for IPU with their latest release. This eliminates one of the patches/hacks I had to implement. Note, here is the current set of [devices they support](https://github.com/Xilinx/aie-rt/blob/release/main_aig/driver/src/global/xaiegbl_defs.h#L46-L54):
```
#define XAIE_DEV_GENERIC_DEVICE		0U
#define XAIE_DEV_GEN_AIE		1U
#define XAIE_DEV_GEN_AIEML		2U
#define XAIE_DEV_GEN_AIE2IPU   	        3U
#define XAIE_DEV_GEN_AIE2P		4U
#define XAIE_DEV_GEN_S100		6U
#define XAIE_DEV_GEN_S200		7U
#define XAIE_DEV_GEN_AIE2P_STRIX_A0	8U
#define XAIE_DEV_GEN_AIE2P_STRIX_B0	9U
```
:sunglasses:

[aie-rt] use `XAIE_DEV_GEN_AIE2IPU`

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir
tests/samples/matmul_peeled_objectfifo.mlir
tests/samples/matmul_peeled_objectfifo_e2e.mlir

-- This commit adds a fix for supporting implicit source/target addressing in amdaie.npu.dma_cpy_nd ops as part of `--iree-amdaie-lower-to-aie` pass.

[AMD-AIE] Support implicit source/target addressing in amdaie.npu.dma_cpy_nd

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPropagateDataLayout.cpp
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.h
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc
sync_deps.py

There are major changes in IREE runtime:
https://github.com/iree-org/iree/commit/dcc8a0d1cce384baf10dd9dd5870f148e02db288
https://github.com/iree-org/iree/commit/f8f299694a81a43a98b2361b2cde95adf0bfe53c
https://github.com/iree-org/iree/commit/9ffe4735c8ed54a622e40b9a16df37657c0417b4
I'm able to build runtime locally with this commit changes. @nirvedhmeshram Could you review this PR and double check the above IREE commits to see if anything is missing?

Bump IREE and MLIR-AIR

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetDirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/tests/amd_aie_target_backend.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir
tests/samples/matmul_peeled_objectfifo.mlir
tests/samples/matmul_peeled_objectfifo_e2e.mlir

This enables passes pre-`aie.device` to retrieve the target AIE device, which I will use in later PRs to lookup hardware-related parameters from the `AMDAIEDeviceModel`.

Add AMDAIEDevice to the executable target config

---

build_tools/ci/cpu_comparison/run_test.sh
build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

This PR adds a test where we use a microkernel for a matmul, and directly generated code for a subsequent elementwise operation -- ie we mix ukernel with direct code generation.

Add e2e and lit tests for ukernel+dcg mix

---

build_tools/ci/cpu_comparison/run_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Fix for bug introduced in https://github.com/nod-ai/iree-amd-aie/commit/7d530aff2146bc5d73e6b051d65f45757aa6c3b2 where aie2xclbin keeps running even after a tool fails. Tested locally.

Make aie2xclbin stop when any intermediate step fails 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir

-- This commit adds Ukernel support in `--iree-amdaie-create-aie-workgroup` pass.
-- The pass is used to create amdaie.workgroup and we can simply skip this processing for a private function declaration.

[AMD-AIE][Objectfifo] Add Ukernel support in create-aie-workgroup

---

runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.cc
runtime/src/iree-amd-aie/aie_runtime/test/DeviceModelTest.cpp

@erwei-xilinx noticed that `deviceModel.isLegalMemtileConnection` was returning legal for `(DMA, 0) -> (South, 4)` even though port/channel 4 isn't a legal channel for `South`. Closer reading of the [relevant fn](https://github.com/Xilinx/aie-rt/blob/d748ddc696702ac7e7e0d2012c93e251add84691/driver/src/stream_switch/xaie_ss_aieml.c#L102) in `aie-rt` shows
> The method assumes both ports exist, and the relevant tile is an MEM-Tile.
So we add a check to see if the ports/channels exist. This of course contradicts mlir-aie at the current commit but it's actually fixed in tip (maybe?).

fix `deviceModel.isLegalMemtileConnection`

---

build_tools/ci/run_matmul_test.sh

Adding a few medium sized matmul tests for the objectFifo flow to the CI as part of a matmul sweep I am doing: https://github.com/nod-ai/iree-amd-aie/issues/556

Add medium sized objectFifo matmul tests

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir

Fixes an issue exposed by a 128x32x64 matmul: https://github.com/nod-ai/iree-amd-aie/issues/556.
In the case of a strided pattern like:
```
offsets: [0, 0, 0, 0] 
sizes: [2, 1, 64, 64]
strides: [4096, 64, 64, 1]
```
the unit dimension (size == 1) in the middle will block the recognition that this is a linear access pattern, resulting in the following canonicalized strided pattern:
```
offsets: [0, 0] 
sizes: [2, 4096]
strides: [4096, 1]
```
If the unit dimension is first removed, the strided pattern can be canonicalized further:
```
offsets: [] 
sizes: []
strides: []
```
meaning a complete linear access.
NOTE: with this fix the above matmul shape is still not functional, but exhibits the same behaviour as `128x32x128` etc

[CanonicalizeDoublyStridedOp] Fix for interleaved unit and linear dims

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetCDODirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/tests/cdo/add_12_i8_using_2d_dma_op_with_padding.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/tests/cdo/add_21_i8_using_dma_op_with_padding.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/tests/cdo/add_378_i32_using_dma_op_with_padding.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/tests/cdo/bad_padding.mlir

This PR adds zero-padding support to our CDO emission utility (port of https://github.com/Xilinx/mlir-aie/pull/1613).
I trimmed the test cases down @erwei-xilinx can you give it a quick look to see if I didn't slip and miss something.
Fixes https://github.com/nod-ai/iree-amd-aie/issues/537
cc @yzhang93 @MaheshRavishankar

Port zero-padding from mlir-aie

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir
tests/samples/matmul_peeled_objectfifo.mlir

Fixes an issue exposed by a 128x32x64 matmul: https://github.com/nod-ai/iree-amd-aie/issues/556.
This issue would come up in partial loop dependencies in case of `scf.forall`:
```
scf.forall (%arg2, %arg3) in (2, 6) {
%1 = amdaie.npu.dma_cpy_nd %0([0, %arg3] [8, 16] [16, 1], [] [] [])
amdaie.npu.dma_wait(%2, S2MM)
}
```
In this case, the outer iteration upon which the NPU DMA operation didn't depend ( `%arg2`) would not be considered, resulting in incorrect output IR:
```
%1 = amdaie.npu.dma_cpy_nd %0([0, 0, 0] [6, 8, 16] [1, 16, 1], [] [] [])
amdaie.npu.dma_wait(%2, S2MM)
```
However, the outer iteration should be considered as well, making sure the above DMA operation is executed twice, resulting in the below output IR:
```
%1 = amdaie.npu.dma_cpy_nd %0([0, 0, 0, 0] [2, 6, 8, 16] [0, 1, …
```

[DmaLoopSubsumption] Fix for strided op in loop without induction var dependency

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

Fixes an issue exposed by a 64x32x128 matmul: https://github.com/nod-ai/iree-amd-aie/issues/556.
As the hardware (AIE2(+)) doesn't support `stride == 0` with buffer descriptors, only a last repeat iteration can be achieved using the repeat count feature. This PR adjusts the DMA loop subsumption pass to optionally not perform any subsumption if this would be violated. For example, the following NPU DMA instruction is not supported on HW:
```
%1 = amdaie.npu.dma_cpy_nd %0([0, 0, %arg3] [8, 2, 16] [16, 0, 1], [] [] [])
```
due to `stride == 0` on the second (middle) dimension. However, the following is:
```
%1 = amdaie.npu.dma_cpy_nd %0([0, 0, %arg3] [2, 8, 16] [0, 16, 1], [] [] [])
```
but the outer repeat dimension needs to be moved to the first/most outer dimension for the AIE lowering …

[DmaLoopSubsumption] Add option to only support repeat on outer dim

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

Fixes incorrect results issues exposed by a 128x32x128 and 256x32x256 matmuls: https://github.com/nod-ai/iree-amd-aie/issues/556.
NPU DMA operations with implicit addressing on L3 side behave incorrectly on some cases and while the correct strides and sizes can be derived from other places, this is quite indirect and easily leads to bugs. For example, in the following case it can be derived from the input `%circ_dma` that the explicit source access pattern is `[0] [1024] [1]` or `[0, 0] [32, 32] [32, 1]` by inspecting at the **target** side of that operation:
```
%circ_dma = amdaie.circular_dma_cpy_nd(%obj0[] [] [], %obj1[] [] []) : (!amdaie.logicalobjectfifo<memref<32x32xi32, 1>>, !amdaie.logicalobjectfifo<memref<1024x1024xi32>>)
...
%npu_dma = amdaie.npu.dma_cpy_nd %circ_dma ([] [] [], …
```

[CanonicalizeDoublyStridedOp] Make single dims explicit by default and require this in LowerToAIE

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAccessToAcquireRelease.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/access_to_acquire_release.mlir

Fix for: https://github.com/nod-ai/iree-amd-aie/issues/582. Ensures deterministic acquire/release order inside AIE cores, which should help with tests and debugging.

[AccessToAcquireRelease] Ensure deterministic acquire/release order

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

Fix for `32x64x32` and `64x64x64` matmul shapes: https://github.com/nod-ai/iree-amd-aie/issues/556.
Some legacy code in in the `DistributeCoresAndObjectFifos` pass that is not really needed is causing DMA operations across the peeled matmul that should map to the same physical channels/ports to be assigned to different tiles on either L2 and/or L3 instead. This is causing issues in the lowering stack as multiple DMAs writing to the same L2 buffer slices is currently not supported. Also, on larger examples this could potentially create resource issues.

[DistributeCoresAndObjectFifos] Fix for L3 distribution across different tiles for same DMAs

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetBCF.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetLdScript.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/chess_intrinsic_wrapper.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/crt.c

Turns out we never needed `me_basic.o` for chess (which automatically links its own) nor do we need it for peano tip (which also automatically links its own libc/crt). So really this PR just ports crt from tip peano for old peano.
Note, this PR doesn't do anything to resolve NA issues we've been having. It merely makes us forward compatible ie we can now generate elfs using both old peano and tip peano (just in the latter case, we don't have NA).

Support chess and peano crt

---

.github/workflows/ci.yml
build_tools/ci/cpu_comparison/input_generator.py
build_tools/ci/cpu_comparison/run_test.py

I was gonna start working on https://github.com/nod-ai/iree-amd-aie/issues/581, which is downstream of one of the comparisons, and I started using the script and then got distracted.

Small cpu_comparison "pythonic" improvements

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo.mlir

In this PR I've updated the KernelDispatch logic to target `ObjectFifo` backend.
Currently we extract `scalingFactor` based on `LHS` type, but a better way is to use the accumulator's element type to do the same. And even better way is to see how to use element types of all the operands. This has already been acknowledged as [a comment in KernelDispatch.cpp](https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp#L159-L169).
In order to not hamper `AIR` backend, this PR therefore uses accumulator's element type to decide the `scalingFactor` for `objectFifo`.
e2e CI test for larger shaped `bf16` as well as `i8` has been added.

[AMD-AIE][Objectfifo] Update KernelDispatch for targeting larger bf16 and i8 Matmul on Objectfifo

---

build_tools/ci/run_matmul_test.sh

-- This commit adds more bf16 and i8 Matmul on ObjectFifio to e2e CI test.

[AMD-AIE][ObjectFifo] Add more e2e CI test for bf16 and i8 Matmul on ObjectFifo

---

build_tools/ci/cpu_comparison/run_test.py
build_tools/ci/cpu_comparison/test_files/depthwise_convolution_i32.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_conv.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Utils/test/UtilsTest.cpp

This PR adds e2d support for i32 convolution, and partial support for i8 and bf16 (we cannot do e2e for types which need vectorization at the moment).

Depthwise convolution (part i)

---

build_tools/ci/cpu_comparison/input_generator.py
build_tools/ci/cpu_comparison/run_test.py

There are some pros and cons of using the llvm-cpu backend as a source of truth for testing the numerical correctness of the code generated for AIE backend. 
Pros: 
- easy (we don't need to write additional code to do convs / matmuls using numpy / torch)
- sort of tests 2 backends at once. If there is a discrepancy between llvm-cpu and aie backends, we might end up fixing a bug in llvm-cpu (less likely than fixing a bug in the aie backend)
Cons:
- additional compile time, and runtime: cannot benefit by sampling results, like IREE does (via run_matmul_test.sh)
- maybe we don't want to rely on llvm-cpu, would prefer to get the source of truth from torch directly, or somewhere else (onnx runtime?) 
This PR basically shows how we can switch the llvm-cpu backend for another source of truth. In …

Ability to use numerics baseline other than llvm-aie

---

build_tools/ci/run_matmul_test.sh

The number of times some of the objectFifo matmul tests are run was recently increased, to flush out our intermittent numerical errors. But the rate of failure in CI has gone above 50%, and this is slowing down developer speed across the board. No one is investigating the numerical issue now, so IMO it doesn't serve any purpose having this increased failure rate in CI. 
This PR lowers the number of repeats for tests (from 10 to 2, or 5 to 2).

Lower number of repeats in matmul tests

---

.github/workflows/ci.yml
build_tools/download_peano.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Related to https://github.com/nod-ai/iree-amd-aie/issues/594, we are getting stuff in `input.opt.ll` that we should not be getting because we are not disabling eg vectorization at the LLVM level.
Note, copy-pasta from [llvm-aie](https://github.com/Xilinx/llvm-aie/blob/0be095354faa49985cd031661853f6d9b9b787f2/clang/lib/Driver/ToolChains/AIE.cpp#L97-L121).

Use correct peano opt flags

---

.github/workflows/ci.yml
build_tools/ci/cpu_comparison/matmul_template/matmul_generator.py
build_tools/ci/cpu_comparison/run_test.py

Changes to cpu_comparison testing:
1) Split AIE compile+run function into 2 functions (so we can repeat just the run step, future work)
2) Add a bit of structure the the tests, by partitioning them into Matmul/Conv/Smoke
3) Add 2 new flags. 
- One to run only one of the above sets of test partition
- One to only partially run the tests (just compile, don't run on AIE HW and do numerical comparison)
4) Add smoke test to CI, which checks that some combination of the flags work as expected

Improvements to cpu_comparison testing

---

.github/workflows/ci.yml

It's useful to people to start these arbitrarily - it works like this:

Enable workflow dispatch for CI tests

---

build_tools/ci/run_matmul_test.sh
runtime/src/iree-amd-aie/driver/xrt/direct_allocator.cc
runtime/src/iree-amd-aie/driver/xrt/direct_allocator.h
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/native_executable.cc
runtime/src/iree-amd-aie/driver/xrt/native_executable.h
runtime/src/iree-amd-aie/driver/xrt/nop_executable_cache.cc
runtime/src/iree-amd-aie/driver/xrt/nop_executable_cache.h
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.h
runtime/src/iree-amd-aie/driver/xrt/xrt_driver.cc

Temporary fix as it seems to work reliably, but needs some follow ups to get rid of the global variable and output buffer sync inside the dispatch function.
Currently, I think there are two separate issues, which are fixed by this PR:
- Hangs, caused by the xrt::device getting destroyed while in use.
- Numerical issues, presumably caused by a missing sync on the output.
Locally, I can do 5000 runs without any issue on my debug shape 32x32x32.

Fix XRT bindings hangs and numerics issues

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

The `amdaie.logicalobjectfifo.access` ops should be ordered right before the first usage, instead of at the beginning of the block. This issue comes up for matmul + elementwise. Existing tests are updated to check for this more carefully.

[DistributeCoresAndObjectFifos] Fix access op ordering in cores

---

compiler/plugins/target/AMD-AIE/aievec/AIEVecToLLVM.cpp
compiler/plugins/target/AMD-AIE/aievec/Passes.h
compiler/plugins/target/AMD-AIE/aievec/VectorToAIEVecConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir
compiler/plugins/target/AMD-AIE/aievec/test/test-ups.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp

Pulls in 2 PRs from mlir-aie for the AIEVec dialect:
1) https://github.com/Xilinx/mlir-aie/pull/1655
2) https://github.com/Xilinx/mlir-aie/pull/1665
Required some changes to pass registration to get the testing working. 
I also did some refactoring specific to our simpler requirements (no AIE1 support, etc)

Port new mlir-aie pattern to iree-amd-aie

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/invalid.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/access_to_acquire_release.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/flatten_logical_objectfifo.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_cores.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/none_access_to_temporary_buffer.mlir

Remove the partially redundant produce/consume ops as they have been largely replaced already with the `logicalobjectfifo.access` ops. The main use for them is to provide information on which cores are using which DMAs which can be handled by adding input and output DMA operands to the `amdaie.core` ops.

Replace logical objectfifo produce/consume with core in/out DMA operands

---

runtime/src/iree-amd-aie/aie_runtime/test/cdo/add_12_i8_using_2d_dma_op_with_padding.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/add_21_i8_using_dma_op_with_padding.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/add_378_i32_using_dma_op_with_padding.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_16x16_8xi32__dispatch_0_matmul_16x1_0.aiecc.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_16x64_32xi8__dispatch_0_matmul_tran_0.aiecc.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_512x512_512xi32__dispatch_0_matmul__0.aiecc.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_64x64_64xbf16__dispatch_0_matmul_64_0.aiecc.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_64x64_64xi8__dispatch_0_matmul_64x6_0.aiecc.mlir
runtime/src/iree-amd-aie/aie_runtime/test/cdo/matmul_8x32_16xi32__dispatch_0_matmul_8x32_0.aiecc.mlir

Use %T (temporary dir) instead of %S (source dir) https://llvm.org/docs/CommandGuide/lit.html
This prevents the 2 .bin files being left in the source tree after testing

[Testing] Don't pollute source tree with artifacts 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

After some refactor of codes, distributeSharedMemory function is no longer needed and generated wrong allocations which caused test failure in https://github.com/nod-ai/iree-amd-aie/pull/652.

[DistributeCoresAndObjectFifos] Remove distributeSharedMemory function

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_cores.mlir

This is a small change to get convolution lowering through the insert core pass. Specifically, it makes sure that linalg::ConvolutionInterfaceOps are handled correctly (in the same way as vector::ContractionOp). I think the pass can be improved further at a later point (we should be able to lift only a subset of the nested loop into the core I think).

[AMDAIEInsertCore] Handle convolution case 

---

build_tools/ci/run_matmul_test.sh

Re-enable commented and add larger vectorized i8 test (with reasonable runtime).

[CI] (Re)enable larger matmul tests

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir

Apply changes in https://github.com/Xilinx/mlir-aie/pull/1675 (hopefully got 'em all)
This PR also inlines `populateCanonicalizeConversionPatterns` to avoid needless indirection. 
FYI: @jsetoain @makslevental

[vectorization] Update aievec after mlir-aie changes

---

runtime/src/iree-amd-aie/aie_runtime/CMakeLists.txt

When building iree-amd-aie with IREE_BUILD_TESTS=OFF, this line generates an error because the target is not being built:
```
CMake Error at /opt/iree/installers/AARInternal/iree-amd-aie/runtime/src/iree-amd-aie/aie_runtime/test/CMakeLists.txt:109 (target_include_directories):
Cannot specify include directories for target
"iree-amd-aie_aie_runtime_test_DeviceModelTestCppTest" which is not built
by this project.
```

Adding conditional statement to remove target_include_directories when tests are not enabled

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELocalizeLogicalObjectFifo.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/localize_logical_objectfifo.mlir

While we probably don't expect an scf.forall without _either_ a thread or block mapping, it's better if this pass can handle the case.

[Localize ObjectFifo] Don't crash when scf.forall has no mapping

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir
experimental/delegate/README.md

Renaming of remaining IPU mentions across compiler and docs. Runtime still uses `IPU` because of `aie-rt`.

Rename IPU to NPU in compiler and docs

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp

Small utility PR to add memory space retrieval to `LogicalObjectFifoType` and prefers using it as it is more general as it would work with any value of this type. Needed for a follow-up in which a new `LogicalObjectFifoPlaceholderOp` will be added, making it unnecessary to distinguish between this new op and `LogicalObjectFifoFromMemrefOp` in a lot of cases.

[LogicalObjectFifoType] Prefer retrieving memory space from type

---

build_tools/ci/cpu_comparison/run_test.py

Also: don't fail if you can't get a peano hash, this isn't strictly needed to run the tests 
FYI @erwei-xilinx

[Testing] Better handling of verbose flag 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir

Doubly strided ops have, for both source and target, and for all of offsets/sizes/strides, 2 fields:
1) a vector of **dynamic** Values
2) a vector of **static** integers
For example it might be
1) dynamic = {v0}
2) static = {16, kDynamic, 32, 64}
The size of **dynamic** is always exactly equal to the number of appearances of kDynamic in the **static** vector. This pass does the following: it checks if any of the Values in **dynamic** are actually MLIR constants, and if they are then it removes the Value from the dynamic vector and updates the corresponding index in **static**. So for example if `v0` above is actually 
```
%v0 = arith.constant 6 : index
```
then this canonicalization updates dynamic/static to 
1) dynamic = {}
2) static = {16, 6, 32, 64}

Canonicalizers for doubly strided ops such as npu.dma_cpy_nd

---

.github/workflows/ci.yml

So that it can be required for merge.

Give linux e2e test a name

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp

What was happening was 
1) Value/Operation inserted into IRMapping
2) IRRewriter erased Value/Op
3) New Value/Op created with same address as erased Value/Op
4) Bad state: new Value/Op is a key in IRMapping, even though it was never added. 
That's my analysis, at least. Either way, this change makes my failure rate go from 10/20 to 0/20. 
An alternative to this PR might be to postpone erasing of ops even longer, so that only after all CoreOps have been processed are the ops erased.

[LowerToAIE] Fix for non-deterministic error (observed with convolution)

---

.github/workflows/ci-linux.yml
build_tools/ci/cpu_comparison/run_test.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h

The Windows E2E PR https://github.com/nod-ai/iree-amd-aie/pull/689 is blocked because in order to get Windows to work I had to use a particular commit of XRT (required by XRT-MCDM). At that commit, the current linux driver (date 20240819) fails some tests while the older driver (such as the one on the sharkbox phoenix nuc) passes. I do not know what the exact issue is but even after a couple recent flake-fixes (https://github.com/nod-ai/iree-amd-aie/pull/697, https://github.com/nod-ai/iree-amd-aie/pull/694), the disparity persists.
This PR XFAILs (effectively) those tests in order to unblock windows E2E. I will reconcile the disparity shortly.
Tracking issue https://github.com/nod-ai/iree-amd-aie/issues/700.
cc @newling

XFAIL failing cpu comparisons

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

This constraint the current convolution pipeline, where there are further memref.subviews which end up with different memspaces on src and dst. 
Removing this constraint doesn't seem to make anything fail, so I'm just removing it.

[LowerToAIE] Don't force change memspace

---

.github/workflows/ci-macos.yml
build_tools/ci/build_test_cpp.sh
compiler/plugins/target/AMD-AIE/aievec/CMakeLists.txt
compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
iree_compiler_plugin.cmake
runtime/src/iree-amd-aie/aie_runtime/iree_aie_configure.cc
runtime/src/iree-amd-aie/aie_runtime/test/CMakeLists.txt
runtime/src/iree-amd-aie/aie_runtime/test/interpreter_op_impl.h

This PR enables MacOS in CI (both x86 and arm64). The purpose is not to enable dev on Mac (although I do dev on my MBP sometimes) but moreso to have another build system to sniff out build issues. Indeed a couple are on display right here. In addition, we discover that one of the `pad_pack_matmul` samples has a bug that is somehow covered up on Linux and only flaky on Windows (on Mac we are a consistent fail).

Enable MacOS in CI

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignNpuDmaBdIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateLogicalObjectFifoLink.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_npu_dma_bd_ids.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

Adds the `amdaie.logicalobjectfifo.placeholder` operation that represents a logical objectFifo to be filled in later. This enables reuse of connections/circular DMAs/physical AIE channels for different data packets, which helps with (fused) operations with more than 2 inputs. This is especially useful for reading from/writing to DDR. 
Before this PR, the circular DMA connections would be always be tied to a HAL buffer on DDR/L3 and the control code NPU instruction could only change the addressing and not the input buffer:
```mlir
%0 = hal.interface.binding.subspan layout(#pipeline_layout) set(0) 
binding(0) alignment(64) offset(%c0) flags(ReadOnly) : memref<1024xi32>
%obj0 = amdaie.logicalobjectfifo.from_memref %0, {%tile_0_0} 
: memref<1024xi32> -> …
```

Add logical objFifo placeholder op for connection reuse

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetLdScript.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Without explicit locations for these sections, they get placed in arbitrary locations. The introduced linker flag will error out if new sections appear (and don't have specific locations/assignments).
See https://github.com/Xilinx/mlir-aie/pull/1717

Fix LdScript emission

---

build_tools/ci/cpu_comparison/run_test.py

Only the multi-kernel tests actually fail

Restore AIR tests

---

.github/workflows/ci-windows.yml

Every 4 hours is a little overzealous - don't want to blow out our cache limit of 10Gb.

Slow down CI-windows cache warming

---

build_tools/ci/run_matmul_test.sh

Not sure what influences this, but locally the `iree-e2e-matmul-test` executable is found under `"${IREE_INSTALL_DIR}/tools/testing/e2e`.

[CI] Add tools/testing/e2e to search dirs

---

compiler/plugins/target/AMD-AIE/aie/AMDAIECoreToStandard.cpp

In case we hit this error again, I'd like the message to be more informative. The new error is something like:
```
<unknown>:0: error: 'arith.constant' op is not in the core in which it is used. Cores must be `isolated` before this point.
<unknown>:0: note: see current operation: %0 = "arith.constant"() <{value = 0 : i32}> : () -> i32
<unknown>:0: error: 'aie.device' op Failed to lower to LLVM
<unknown>:0: note: see current operation:
"aie.device"() <{device = 8 : i32}> ({
```
compared to old error, something like: 
```
LLVM ERROR: operation destroyed but still has uses
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var …
```

[AMDAIECoreToStandard] Improve error message when core not isolated 

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml
build_tools/ci/build_test_cpp.sh

GHA (github action) [caches](https://github.com/nod-ai/iree-amd-aie/actions/caches) aren't mutable so currently we're timestamping them:
```
windows-build-test-cpp-asserts-v1-f77db6670966b372878b4219599ba723feb41945-2024-08-28T19:33:14Z
```
Thus PRs that run will upload new caches and push out old but useful caches, e.g., caches from main that could be used by PRs. 
~~This PR tries to mitigate that by using either PR number (in case the cache is produced by a PR) or `github.ref_name-N` where `N` always increments (in case the cache is produced by a branch run, like cache warming on `main`) to label the cache. The overwrite is done by first deleting any existing cache by that name and then uploading the new cache to the same label/key.~~
~~So PR caches look like this~~
``` …
```

Fix GHA caches

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

When chess is enabled, the core elf generation returns early instead of generating an elf for all cores, leading to the following error:
> Run:  PATH=/home/jorn/workspace/Vitis/2024.2/aietools/tps/lnx64/target_aie2p/bin/LNa64bin:/opt/xilinx/xrt/bin:/opt/xilinx/xrt/bin:/home/jorn/miniconda3/bin:/home/jorn/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin LD_LIBRARY_PATH=/home/jorn/workspace/Vitis/2024.2/aietools/lib/lnx64.o:/home/jorn/workspace/Vitis/2024.2/aietools/lnx64/tools/dot/lib:/opt/xilinx/xrt/lib:/opt/xilinx/xrt/lib RDI_DATADIR=/home/jorn/workspace/Vitis/2024.2/aietools/data XILINXD_LICENSE_FILE=/home/jorn/workspace/iree-amd-aie/../Xilinx.lic /home/jorn/workspace/Vitis/2024.2/aietools/bin/unwrapped/lnx64 …

[XCLBinGen] Fix chess core elf generation

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

This PR adds the ability to SSH into runners using https://github.com/mxschmitt/action-tmate. The way it works is like this:
1. You want to debug a runner either because it failed or for the heck of it;
2. You go to the `Actions` tab and find the list of actions in the left colum and select Mac or Windows (**but not Linux** - see Notes below): 
3. You then go to the far right and click the `Run workflow` dropdown:
Note, the `Branch:` dropdown - currently (because this PR hasn't landed) I can only do it for this branch. After this PR lands you'll be able to do it for any branch;
5. You check either one of the options; hopefully the descriptions are sufficient - if not ask in this PR and I'll update the descriptions accordingly;
6. The runner will run to completion or failure and then, **at …

SSH into runners

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Fix CI for forks

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateLogicalObjectFifoLink.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_logical_objectfifo_link.mlir

In a larger change to start extracting `aie.flow` ops from `AMDAIEStatefulTransform`, I ran into a segfault issue inside the walk to remove non-zero offsets. I extracted the fix from that effort to reduce the scope of that PR.

[CreateLogicalObjFifoLink] Refactor unsafe walk for non-zero offset removal

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignNpuDmaBdIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECoreLoopUnroll.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateLogicalObjectFifoLink.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFusePackIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETile.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp

- Update `dyn_cast` to `dyn_cast_if_present` everywhere getDefiningOp is used
- Update `isa` to `isa_and_present ` everywhere getDefiningOp is used
- Update `dyn_cast_or_null` to `dyn_cast_if_present` because the former is deprecated (see below)
- Update `isa_and_nonnull` to `isa_and_present` because although not deprecated according to comments, the former calls the latter under the hood and to be consistent with `dyn_cast_if_present`
`dyn_cast_or_null` is deprecated (https://llvm.org/doxygen/Casting_8h_source.html):
> // Forwards to dyn_cast_if_present to avoid breaking current users. This is
// deprecated and will be removed in a future patch, use
// cast_if_present instead.
template <class X, class Y> auto dyn_cast_or_null(const Y &Val) {
return dyn_cast_if_present<X>(Val);
}

Use dyn_cast_if_present and isa_and_present with getDefiningOp

---

.gitmodules

Main motivation for this is to make switching between branches faster: Down from 15 seconds to light-speed.
For things like `git status` and `git diff` I've figured out how to make them fast without this change: use the `--ignore-submodules` flags. But for `git checkout` I haven't found an equivalent. 
I guess the underlying problem is that the submodules (XRT, etc.) get dirtied after cloning, and somehow this makes more work for `git`. Untracked files like  `src/runtime_src/core/common/api/version.h` etc appear. I'm not 100% sure of this. 
If someone has an alternative suggestion to getting lighting fast `git checkout` without this PR: please let me know.

[gitmodules] Ignore dirty submodules

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir

This works for now because the sizes of dimensions `DimZ` and `LinearDim0` are 1 with our tiling strategy, and so `DimY` and `DimX` map to the rows and columns of the AIE array. Follow-up work: pass to collapse scf.forall's with more than 2 induction variables to just 2. So instead of 
`(i,j,k) in (2,3,5)` 
for example, could be
`(i,l) in (2,15)` and then j=l/5 k=l%5.

[TileAndFuse] Add thread groups for convolution ops 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELogicalObjFifoSplittingUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESplitLogicalObjFifosForConnectionReuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

-- This commit adds refactoring of few utilities in DmaUtils as well as a few involved in SplitLogicalObjectFifosForReuse pass.
-- This is required for the follow-up PR that adds a new pass `--iree-amdaie-combine-logical-objectfifos-for-connection-reuse`.

[ObjectFifo][NFC] Refactor DmaUtils + SplitLogicalObjectFifoForReuse

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.h

Fixes a small inconsistency in the `AMDAIECreateAIEWorkgroup` pass I came across.

[CreateAIEWorkgroup] Make buildForCoreOp a member method for consistency

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECoreLoopUnroll.cpp

Adds the `getDepth` method to the `LogicalObjFifoOpInterface`. Also updates the `getTiles` return type to `ValueRange`, which makes the method easier to implement for logical objectFifos that don't have the tiles as operands themselves. This PR is prefetching some general changes needed to introduce a new logical objectFifo op which is created from a set of buffers, which I need for moving the bulk of the `StatefulTransform` logic into the `AMDAIE` dialect.

[LogicalObjFifoOpInterface] Add getDepth method

---

.github/workflows/ci-linux.yml

This PR makes the order of tests on linux
```
E2E comparison of AIE to llvm-cpu
E2E correctness matmul test
Printing IR from aie2xclbin
Smoke E2E comparison flag test
```
'smoke' test last because it's testing with verbose=0, not a good test to run first because diagnosing unrelated failures is impossible.

[CI] reorder tests in linux CI to make debug easier

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/AMDAIEDmaOpInterfaceTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/CMakeLists.txt

Add static size retrieval methods to the `AMDAIEDmaOpInterface`.
Needed as part of a larger effort to remove `StatefulTransform`: https://github.com/jtuyls/iree-amd-aie/tree/delete-stateful-transform

[DmaOpInterface] Add static size retrieval method

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEDmaToNpu.cpp
compiler/plugins/target/AMD-AIE/aie/test/dma_to_npu.mlir

From: https://github.com/Xilinx/mlir-aie/pull/1671/files#diff-2dc661023141402b83d465f580b2aa2e72aad010c1b19da829d1e014fd2d324cR373
Adds packet routing support for `NpuDmaMemcpyNdOp`.

[DmaToNpu] Add packet support for NpuDmaMemcpyNdOp

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertToDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/convert_to_dma.mlir

Inverse permutation needs to be applied when converting unpack to DMA, not permutation. PR adds test with permutation P != P^{-1}, without which this bug is hidden. I've left a comment with that test explaining why this fix is required. Also, `--cse`  is removed from the test lit command, to reduce noise.

[ConvertToUnpack] Apply correct permutation when lowering unpack to DMA

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

As of 2024.2, Chess has caught up to LLVM. This will unblock https://github.com/nod-ai/iree-amd-aie/pull/732 (i.e., aiesimulator support).

Remove `chesshack`

---

compiler/plugins/target/AMD-AIE/aie/test/test_congestion0.mlir
compiler/plugins/target/AMD-AIE/aie/test/test_congestion1.mlir
compiler/plugins/target/AMD-AIE/aie/test/test_pktflow_weight_pusher.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignConnectionTypes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_connection_types.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.cc

Pulls in changes from: https://github.com/Xilinx/mlir-aie/pull/1694
This fixes deadlock issues with larger matmuls when all connections are made packet connections and therefore enables optional packet routing on all connections.

[Router] Add packet flow groups for channel sharing

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir

There's a pass we run `--canonicalize-vector-for-aievec` which (as the name suggests) massages vector dialect operations to make them lowerable to aievec. One of the things the pass does is 'flatten' `vector.transfer_read`s. For example it converts 
```  
%26 = vector.transfer_read %reinterpret_cast_1[%c0, %20, %24, %22, %c0], %cst {in_bounds = [true, true]} : memref<1x3x4x6x8xbf16>, vector<4x8xbf16>
```
which has a rank-2 vector operand to 
```
...
%collapse_shape = memref.collapse_shape %reinterpret_cast_1 [[0], [1], [2], [3, 4]] : memref<1x3x4x6x8xbf16> into memref<1x3x4x48xbf16>
%27 = vector.transfer_read %collapse_shape[%c0, %20, %24, %26], %cst {in_bounds = [true]} : memref<1x3x4x48xbf16>, vector<32xbf16>
%28 = vector.shape_cast %27 : vector<32xbf16> to vector<4x8xbf16>
``` …

[AIEVec] Allow unit extent dimensions in canonicalize-vector-for-aievec

---

build_tools/ci/cpu_comparison/run.py
build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertCoreForallToFor.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/convert_core_forall_to_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop_scf_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop_scf_forall.mlir
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
tests/conftest.py
tests/test_matmul.py

-- IREE Bump to 18th Sep, 2024

IREE Bump to Oct 1, 2024

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertToDma.cpp

Introduced and unaddressed in https://github.com/nod-ai/iree-amd-aie/pull/812

Don't capture this unnecessarily 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETemporaryAllocBufferization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/temporary_alloc_bufferization.mlir

Update the pass to handle `memref.alloc` in any scope, not just in `amdaie.core`

[AMDAIETemporaryAllocBufferization] Bufferize temporary allocs that aren't defined in core

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/AMDAIEDmaOpInterfaceTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/invalid.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignNpuDmaBdIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeNpuDmaCpyNd.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_npu_dma_bd_ids.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_npu_dma_cpy_nd.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_composition.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/obj_fifo_bufferization.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/remove_memory_space.mlir

This PR makes the return type of `AMDAIE::NpuDmaCpyNdOp` optional and more explicit by introducing an `amdaie.async_token` type. The `AMDAIE::NpuDmaWaitOp` will now operate on operands of the async token type . This is consistent with how `gpu.async_token` is used in the GPU dialect.

[NpuDmaCpyNdOp/NpuDmaWaitOp] Return optional async token and wait for multiple

---

build_tools/ci/cpu_comparison/input_generator.py
build_tools/ci/cpu_comparison/test_input_generator.py

-- This commit adds a quick fix for bf16->f32 utility to preserve the shape of the input.
-- Without this the utility is linearizing the input which causes issues during comparison.

[Testing] Fix bf16->f32 utility to preserve shape of the input

---

build_tools/ci/cpu_comparison/input_generator.py
build_tools/ci/cpu_comparison/run.py
build_tools/ci/cpu_comparison/test_input_generator.py

llvm-cpu `truncf` rounds up when it should round down, this PR allows us to circumvent this issue by testing with hand-crafted inputs and expected output. See https://github.com/nod-ai/iree-amd-aie/pull/829#issuecomment-2397302993

[Testing] e2e numerical test with user defined inputs and expected value

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/conv2d_nhwc_objectfifo_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_conv.mlir

This PR switches all numerical convolution tests to use the objectFifo pipeline. With respect to the new tiling strategy:
1) A single **column** is currently used. Targeting multiple columns results in ` error: 'aie.memtile_dma' op could not find and assign a valid BD id`. This will will be investigated as follow-up work: https://github.com/nod-ai/iree-amd-aie/issues/821
2) There is no longer interleaving of compute and L2->L1 data movement, which means https://github.com/nod-ai/iree-amd-aie/issues/619 becomes low priority / obsolete
3) L3->L2, L2->L3 still uses padding. But L2->L1, L1->L2 uses packing. 
4) Channel-first convolution is completely unsupported, we expect high level transforms to convert to channel last before reaching our backend. 
5) Vectorization is not currently enabled, …

[Convolution] Packing + objectFifo, initial support

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETemporaryAllocBufferization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir

This PR adds a corner case for strided op combination. With this PR, the following strides ops:
```
48 = amdaie.npu.dma_cpy_nd %8([] [] [], %31[0, %45] [32, 64] [128, 1]) : source_type = !amdaie.logicalobjectfifo<memref<16384xi32>>
%49 = amdaie.npu.dma_cpy_nd %8([] [] [], %31[32, %45] [96, 64] [128, 1]) : source_type = !amdaie.logicalobjectfifo<memref<16384xi32>>
```
can be combined as 
`%48 = amdaie.npu.dma_cpy_nd %8([] [] [], %31[0, %45] [128, 64] [128, 1]) : source_type = !amdaie.logicalobjectfifo<memref<16384xi32>>
`
Addressed review comments https://github.com/nod-ai/iree-amd-aie/pull/826#discussion_r1792561366.

[CombineStridedOps] Add a combinable case

---

compiler/plugins/target/AMD-AIE/aie/AMDAIECoreToStandard.cpp

Main motivation: the dialect legalization stuff is making it difficult to move the llvm passes into the main IREE pipeline. Why do I want to do that? So that I can control [this pass](https://github.com/nod-ai/iree-amd-aie/blob/be42d1918f43ed04595a1384cd9274305e42f961/compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp#L965) better. Why? Because to get vectorization semi-working for convolution I'd like to be better able to control when that pass runs, ie pull it out of aie2xclbin.

[AMDAIECoreToStandard] Pass simplification

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp

To get this fix https://github.com/iree-org/iree/pull/18831

Bump IREE to df5e5aab044ed5b6c5860b0b291c95eafe1c2522

---

build_tools/ci/run_matmul_test.sh
runtime/src/iree-amd-aie/driver/xrt-lite/api.h
runtime/src/iree-amd-aie/driver/xrt-lite/device.cc
runtime/src/iree-amd-aie/driver/xrt-lite/device.h
runtime/src/iree-amd-aie/driver/xrt-lite/registration/driver_module.c
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/device.cpp
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/device.h
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/hwctx.cpp
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/hwctx.h

Notes
1. This needs `sudo`;
- if you want to run the whole `run_matmul_test.sh` script under `sudo` and you have env variables you need to do `sudo -E`;
2. I remembered this can actually be done using `xrt-smi` with something like 
```
sudo /opt/xilinx/xrt/bin/xrt-smi configure -d 0000:c5:00.1 --pmode turbo
```
Still maybe this is useful to expose directly here so that `xrt-smi` isn't required in the env.
Using the added test I got these results:
```
-----------------------------------------------------------------------------------------------------------------
Benchmark                                                       Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------- …
```

[XRT-LITE] add ability to configure NPU power mode

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/DecomposeLinalgExtPackUnPackToAIR.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_to_air.mlir
tests/test_matmul.py

- Convolution with `air` pipeline now works once again.
- In MLIR-AIR, we now have a ukernel for vectorized i8 conv2d (https://github.com/Xilinx/mlir-air/blob/main/test/xrt/14_conv2d_i8_extern_vec/aie.py), following the new convolution tiling recipe in iree-amd-aie.

Bump mlir-air to 24cb14e6d2233e819a5455928e4237ef319e6fc8

---

README.md
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/amdxdna_accel.h
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/bo.cpp

Pulls in changes from https://github.com/amd/xdna-driver/commit/6d187619e67bf85c694649dc14a1d0465c587091 to make `xrt-lite` work with the latest driver kernel module (see README in changes).
I will need to bump the driver modules on the CI runners to get this PR passing.

Bump driver dependency

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

This PR does 2 things:
1) moves aievec lowering **_before_** scf-to-cf, because computing the alignment information needed to support convolution vectorizion in cf is more difficult than in scf. 
2) Makes flattening of `transfer_read` ops more "aggressive". Large c&p from upstream MLIR here, sorry. Read on for more info. 
The current convolution workflow ends up with core code to load from the input image that looks like:
```
scf.for %arg1 = %c0 to %c3 step %c1 {
scf.for %arg2 = %c0 to %c3 step %c1 {
scf.for %arg3 = %c0 to %c4 step %c1 {
%0 = vector.transfer_read 
%reinterpret_cast_54[%c0, %arg1, %arg3, %arg2, %c0], %cst 
{in_bounds = [true, true]} : memref<1x3x4x6x8xbf16>, vector<4x8xbf16>
... 
}
}
}
```
What is the alignment of the transfer_read above? In other words, what is the …

Towards vectorized convolution (first PR)

---

compiler/plugins/target/AMD-AIE/aievec/AIEVecOps.cpp
compiler/plugins/target/AMD-AIE/aievec/AIEVecOps.td
compiler/plugins/target/AMD-AIE/aievec/test/fold-ops.mlir

ShiftOp has 2 64 byte vector operands, and 1 64 byte vector result. The result is a concatenation of the N upper bytes from the first operand, and the 64 - N lower bytes from the second operand. This folder considers the special cases where N = 0 and N = 64, when it is possible to just return one of the operands directly. 
https://www.xilinx.com/htmldocs/xilinx2024_1/aiengine_ml_intrinsics/intrinsics/group__intr__gpvectorop__shift.html#gaa83afc81114a5e0d3aebea1e973248bc

[aievec] ShiftOp folder 

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_elementwise_pack_peel_objectfifo_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertLoopsForVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_loops_for_vectorization.mlir

-- This PR adds the following pieces to enable working of larger Matmul + Truncf.
1. Updates `insert-loops-for-vectorization` to work on bufferized inputs, collapse unit dimensions and coalesce the generated loops for tiling.
2. Makes the pipeline as `IREEComprehensiveBufferization` -> `insert-cores` -> `insert-loops-for-vectorization` -> `vectorization`.
3. Creates and adds a new pass `function-outlining` - which is invoked right after `insert-cores` pass.
4. Adds two canonicalization patterns that canonicalizes away trivial read/write access patterns to enable other dependent canonicalizations in `aievec`.
5. Adds e2e CI test for 128x128x256 Matmul + Truncf bf16 -> bf16.

[Vectorization][ObjectFifo] Enable larger Matmul + Truncf

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeNpuDmaCpyNd.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECombineStridedOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaComposition.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Transforms.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op_hardware_aware.mlir

Canonicalization of the offsets/strides/sizes in doubly-strided operations, like DMA ops, can lead to overflow of the number of available bits in the hardware buffer descriptor fields. This PR adds logic to the `AMDAIECanonicalizeDoublyStridedOpPass` to not canonicalize if it would lead to such an overflow.
Note that there is more work to be done on avoiding overflow of available hardware bits and making it more robust, which is not addressed in this PR:
- Using aie-rt's transaction data structure and APIs to generate the control code transaction instead of the manual transaction creation we're currently doing: https://github.com/nod-ai/iree-amd-aie/blob/20867183c610ec870344d074c4be78e0aaac1515/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeToTransaction.cpp#L33. …

Add hardware-aware canonicalization

---

build_tools/ci/cpu_comparison/convolution_template/convolution_generator.py
build_tools/ci/cpu_comparison/matmul_template/matmul_generator.py
build_tools/ci/cpu_comparison/run.py

After this PR it is possible to run individual tests. 
```
./run.py --help 
```
Prints
```
...
--tests TESTS         A comma-separated list of test names or sets to run. Available test sets: BatchMatmul, Convolution, ConvolutionNHWCQ, Matmul, MatmulFullBias, MatmulThinBias, MatmulTruncf, MultipleDispatches, UKernel, VanillaMatmul, All. Available individual tests: batch_matmul_1_128_128_256_bf16_f32, batch_matmul_1_128_128_256_i32_i32,
batch_matmul_2_64_64_64_bf16_f32, batch_matmul_2_64_64_64_i32_i32, conv_2d_nhwc_hwcf_2_14_bf16_f32, conv_2d_nhwc_hwcf_2_14_i32_i32, conv_2d_nhwc_hwcf_2_14_i8_i32, convolution_nhwc_q, depthwise_conv_2d_nhwc_hwc_1_14_i32_i32, matmul_f32_8_4_8, matmul_f32_8_8_4, matmul_full_bias_128_128_256_i32_i32,
matmul_thin_bias_1024_1024_512_bf16_f32_ukernel0, …
```

[Testing] Make it possible to run individual tests 

---

.github/workflows/ci-linux.yml
.github/workflows/ci-windows.yml
build_tools/ci/cpu_comparison/run.py
build_tools/ci/run_all_runtime_tests.sh

To start enabling strix, add an explicit flag to pass the target device to the test config.

[CI][Test] Add `target_device` flag

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/align-transfer-reads.mlir

I've checked that the IR of a matmul (32x32x64 bf16) is now unchanged by this alignment pass. This this PR, there were aievec.ext ops remaining in the IR after this pass for matmuls. So I'm confident this resolves https://github.com/nod-ai/iree-amd-aie/issues/882

[aievec] Don't add alignment ops if already aligned 

---

.github/workflows/ci-linux.yml
build_tools/ci/cpu_comparison/run.py

-- This commit updates run.py to create test instances specifying
the intended target device(s) to run them on. And accordingly run
only those test instances whose intended target device list matches
the supplied command-line arg `target_device`.
Keeping this PR logically separate from the Strix ukernel one - helps compartmentalizing.

[Test] Update run.py to run only `target_device` specific tests

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pack_peel_objectfifo_ukernel_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

Reverts nod-ai/iree-amd-aie#846, which somehow leads to a bit regression for vectorization path on ToM, although it wasn't causing regression when I tried it with HEAD @ 13d20252d4743ab7b6816572fbcb9aefbb7ffe7a.

Revert "Increase the K tile size in L1 for matmul ops"

---

.github/workflows/ci-linux.yml
build_tools/build_test_cpp.sh
build_tools/ci/cpu_comparison/performance_summarizer.py
build_tools/ci/cpu_comparison/run.py
runtime/src/iree-amd-aie/driver/xrt-lite/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt-lite/direct_command_buffer.cc

I'll remove some spacing, but above is where you can see the kernel execution time in the CI logs. 
Alternatives considered:
1) Suggestion here: https://github.com/nod-ai/iree-amd-aie/pull/892#discussion_r1838636704 very nearly worked, but it resulted in large amounts of trace information being written to terminal, which I was worried would swamp the CI logs. Played around with `IREE_TRACING_CONSOLE_FILE` but not really designed for this. 
2) Tried tracy, but there is no simple text file dumped with tracy (as far as I can tell) so this didn't work 
3) Tried making a standalone test based on https://github.com/nod-ai/iree-amd-aie/blob/main/runtime/src/iree-amd-aie/driver/xrt/cts/matmul_dispatch_test.cc but this got more complicated than I could handle. 
FWIW running the m=n=512 k=4096 …

Invasively print kernel execution time, percolate to CI output

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeToTransaction.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/controlcode_to_transaction.mlir

The address generation for the `PushToQueue` op is incorrect for `column != 0` and `row == 0` as the condition `col && row` is not true. There is not need for this condition and the base tile address can always be computed as `((col & 0xff) << colShift) | ((row & 0xff) << rowShift)`, see:  https://github.com/Xilinx/aie-rt/blob/3fdf8d8d9a7a2abcd8df76155f950680607eac8a/driver/src/common/xaie_helper.h#L159
Note that we don't see this issue in main right now and this is prefetching an issue that's occurring on 4x4.

Fix bug in PushToQueue address generation

---

build_tools/ci/cpu_comparison/run.py

- make `aie_compilation_flags` test specific (undoes mixing of local/global state of https://github.com/nod-ai/iree-amd-aie/pull/908)
- use above to simplify code controlling function outlining, coalescing, etc 
- reuse logic of when to run ukernel (move to base class) 
- remove return-on-fail flag (always return on fail)

[CI] run.py improvements 

---

build_tools/ci/cpu_comparison/performance_summarizer.py
build_tools/ci/cpu_comparison/run.py

Now prints performance numbers for shapes
(M, N, K) = (512, 512, 4096) and (512, 4096, 512) and (4096, 512, 512)
with and without ukernels. Numbers with ukernels are interesting, take a look in CI, different gain with ukernel for the different shapes. 
But looks like there's some improvement we can make on the vectorization of matmul front.

[CI] Add new shape and with/without ukernel for benchmark tracking

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAccessToAcquireRelease.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAcquireReleaseToUseLock.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/access_to_acquire_release.mlir

Before this PR, the logic for read access was invalid. Code like 
```
for i in range(10):
read_access
read_access
```
got transformed to 
```
for i in range(10):
acquire
read_access
release
acquire
read_access
release
```
As you can see above, the code ignored the scoping of the accesses. This PR ensures that acquires and releases are inserted in the same scope.

[AMDAIEAccessToAcquireRelease] Insert acquire/release pairs in same scope

---

build_tools/ci/cpu_comparison/run.py

Changes the file dir variable to contain an absolute path. The relative path gives me issue locally, for example: `build_tools/ci/cpu_comparison/matmul_template/matmul_truncf_MxK_KxN.mlir` not found when I run with:
```
python3 build_tools/ci/cpu_comparison/run.py \
test_aie_vs_cpu \
../iree-build/ \
path-to-llvm-aie \
--vitis-dir path-to-vitis \
--xrt_lite_n_core_rows=$XRT_LITE_N_CORE_ROWS \
--xrt_lite_n_core_cols=$XRT_LITE_N_CORE_COLS \
--tests "All" \
--target_device "npu1_4col" \
-v
```

[Test] run.py make file dir absolute

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeL1Allocations.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_l1_allocations.mlir

There was what appeared to be a false positive error in CI. i.e. an op emits an error somewhere, but the end-to-end numerical test still passes:
I tracked this down and fixed it. 2 things: 
1) error wasn't being propagated all the way to the signal pass failure
2) the convolution tiling doesn't use the approach where L1 result tensors are initially of shape <4x4x*> and then distributed to tensors of shape <1x1x*> but the logic wasn't quite right and it was trying to do this for conv. 
1 was hiding 2, causing default behaviour which just happened to work.

[DistributeL1Allocations] Fix logic for conv and correctly propagate errors

---

compiler/plugins/target/AMD-AIE/aie/AMDAIECreatePathFindFlows.cpp
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.cc
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.h
runtime/src/iree-amd-aie/aie_runtime/test/test_amsel_generator.cc

One of two PRs needed to fix the packet routing issue for 4x4: https://github.com/nod-ai/iree-amd-aie/pull/920
Adds a direction field to the `PhysPort` struct to distinguish between ports on the source and destination side of a switch box. This avoids that they are being recognized as the same port while assigning amsel values. See the testcase being added.

Add direction to physport to separate source and destination ports

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELogicalObjFifoSplittingUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESplitLogicalObjFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

Generalizes the logical objectFifo splitting analysis to find a source, target and objectFifo splitting dimensions. Enables to pass to demonstrate correct functionality on all tests and especially batch matmul.

[SplitLogicalObjFifos] Generalize splitting analysis and enable pass in pipeline

---

.github/workflows/ci-linux.yml
.github/workflows/ci-windows.yml
build_tools/ci/cpu_comparison/run.py
build_tools/ci/run_all_runtime_tests.sh
build_tools/ci/run_matmul_test.sh

- Make flag usage consistent (use_this_format instead of this-format uniformly)
- Simplify run_matmul_tests.sh -- remove all peano/vitis/ukernel path testing, move all these tests to run.py 
- Make the use_chess flag test specific, rather that a global config flag 
- Change `VanillaMatmul` label to just `Matmul`

[CI] Refactor tests with chess 

---

runtime/src/iree-amd-aie/driver/xrt-lite/cts/CMakeLists.txt

We have a test which runs iree-compile at IREE compile time, and it prints alot of stuff to terminal because it has a specific flag enabled. This PR lowers the verbosity by removing the flag 
i.e. when you run `ninja` or `make` in the terminal you see: 
```
Run:  ... cts/module_amdaie_fb_amdaie_pdi_fb/core_1_4.elf -v
Succeeded in totalTime 0.000000e+00 [s]. Exit code=0
clang version 19.0.0 (https://github.com/Xilinx/llvm-aie 562ccea2c9b29e68756e2ae5fe3c22e764e40f20)
Target: aie2-none-unknown-elf
Thread model: posix
... ule_amdaie_fb_amdaie_pdi_fb/core_1_4.elf
```
now removed.

[NFC] Remove terminal printing during IREE build

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignTiles.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_tiles.mlir

Generalize `AMDAIEAssignTiles` to use `LogicalObjFifoInterface` and `CopyOpInterface` where possible. This allows this pass to be moved around more within the pass pipeline.

[AssignTiles] Generalize pass to use LogicalObjFifoInterface and CopyOpInterface

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

Before, certain files were overwritten between tests, if the dispatch operation was the same. Now, no files are overwritten. Each test now has a subdirectory containing all its files (and no further subdirectories). i.e. now it is something like
```
output_dir
├── conv_2d_nhwc_hwcf_2_14_bf16_f32
│   ├── aie_cdo_elfs.bin
│   ├── aie_cdo_enable.bin
│   ├── aie_cdo_init.bin
...
│   ├── module_f_conv_dispatch_0_amdaie_pdi_fb_benchmark.mlir
│   └── module_f_conv_dispatch_0.mlir
├── conv_2d_nhwc_hwcf_2_14_i32_i32
│   ├── aie_cdo_elfs.bin
...  ...
└── depthwise_conv_2d_nhwc_hwc_1_14_i32_i32
├── aie_cdo_elfs.bin
├── aie_cdo_enable.bin
├── aie_cdo_init.bin
├── configured_module_f_conv_dispatch_0.mlir
├── core_0_2.elf
...
└── module_f_conv_dispatch_0.mlir
```
Motivation: I'm running a set of tests …

[NFC] Improve directory structure for test generated files

---

build_tools/ci/cpu_comparison/run.py

I think we should be testing we threading on, so that if we do introduce something which doesn't work with multiple threads we'll know about it immediately.

[CI] don't disable threading in compiler

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELinalgFunctionOutlining.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/linalg_function_outlining.mlir

Before this PR, batch matmul and convolution didn't behave as expected. 
batch matmul: an error was emitted but not propagated to signal a pass failure, so the pass quietly continued
convolution: at the point of function outlining the convolution has already been decomposed into a rank-3 matmul. So it was being outlined as a matmul. Which is fine, except the generic being outlined was
```
linalg.generic {indexing_maps = [#map2, #map3, #map4], 
iterator_types = ["parallel", "parallel", "reduction"]} 
ins(%subview_20, %subview_18 : memref<4x8xbf16, strided<[8, 1], offset: ?>, 2 : i32>, 
memref<8x4xbf16, strided<[4, 1], offset: ?>, 2 : i32>) ... 
```
which has layouts on the memrefs. Outlining this without adjusting the types in the pass results in the error
```
error: 'llvm.call' op …
```

Changes needed to enable outlining by default 

---

compiler/plugins/target/AMD-AIE/aie/AIEDialect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

Make the dimension folding inside `LowerToAIE` partially hardware-aware by retrieving max sizes from the device model. This avoids overflowing the number of available bits.
A few notes:
- This folding inside `LowerToAIE` is needed at this place and can't be done separately earlier right now because offsets can be assumed all zero here because they are already handled earlier in this pass. We should try to streamline this further in the future so that this one-off folding is not needed. This can be done for example by canonicalizing on the lowered ops instead.
- Similar checks should be done for strides as well. I can do this in a follow-up.

[LowerToAIE] Make size folding hardware-aware

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption_circular.mlir

Fixes the logic to block loop subsumption to only check for users within the current scope and refactors the code a bit.
Example of a case which is now supported:
```
%0 = amdaie.connection(%arg0, %arg1) : (!amdaie.logicalobjectfifo<memref<1x1x8x16xi32>>, !amdaie.logicalobjectfifo<memref<8x16xi32, 1>>)
amdaie.controlcode {
scf.for %arg2 = %c1 to %c6 step %c2 {
%2 = amdaie.npu.circular_dma_cpy_nd %0([0] [16] [1], [] [] [])
}
%3 = amdaie.npu.circular_dma_cpy_nd %0([0] [32] [1], [] [] [])
amdaie.end
}
```
With expected output:
```
%0 = amdaie.connection(%arg0, %arg1) : (!amdaie.logicalobjectfifo<memref<1x1x8x16xi32>>, !amdaie.logicalobjectfifo<memref<8x16xi32, 1>>)
amdaie.controlcode {
%2 = amdaie.npu.circular_dma_cpy_nd %0([0] [16] [1], [] [] [])
%3 = amdaie.npu.circular_dma_cpy_nd %0([0] …
```

[DmaLoopSubsumption] Limit blocking of subsumption of circular dma op to same scope

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELinalgFunctionOutlining.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/linalg_function_outlining.mlir

This is a fix for a bug I introduced in https://github.com/nod-ai/iree-amd-aie/pull/951 . I thought that the approach of removing the offset from the memref function signature worked, but it doesn't seem to. I must have been running a test other than the convolution end-to-end test when I was confirming it worked - now with function outlining enabled in gives a numerical error. 
This PR simplifies logic: any non-identity layout results in no outlining.

[AMDAIELinalgFunctionOutlining] Don't outline if operand has non-identity layout 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/conv2d_nhwc_objectfifo_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_elementwise_pack_peel_objectfifo_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pack_peel_air_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pack_peel_objectfifo_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pack_peel_objectfifo_ukernel_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pad_pack_air_e2e.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

This PR did some cleanup of tests including
- Changed the test flags in `Test/samples` to use `--compile-to=executable-targets` instead of `--compile-to=executable-sources` and get rid of a mixture use of `iree-compile` and `iree-opt`.
- Removed redundant (with default value) flags.
- Modified some `//CHECK` tags to keep consistent format.

[Tests] Simplify test flags

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir

Add support in the `CombineStridedOpsPass` for the case when all dimensions, except possibly the first one, are the same.
Example:
```
amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0] [8, 16] [8, 1])
amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0] [8, 16] [8, 1])
```
is transformed into:
```
amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0, 0] [2, 8, 16] [0, 8, 1])
```
Another example:
```
amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0, 0] [16, 8, 16] [32, 8, 1])
amdaie.npu.dma_cpy_nd %0([] [] [], [1, 0, 0, 0] [2, 16, 8, 16] [64, 32, 8, 1])
```
is transformed into:
```
amdaie.npu.dma_cpy_nd %0([] [] [], [0, 0, 0, 0] [3, 16, 8, 16] [64, 32, 8, 1])
```

[CombineStridedOps] Add support for same values

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp

I missed a case for `size(A) > size(B)` in https://github.com/nod-ai/iree-amd-aie/pull/963.
If `size(A) > size(B)` and `stridesA[0] == 0` and all other dimensions are equal, then access pattern A contains N repetitions of access pattern B and they can be combined into a single access pattern with N+1 repetitions.
Example:
```
A: offsets: [0, 0], sizes: [7, 16], strides: [0, 1]
B: offsets: [0], sizes: [16], strides: [1]
```
is transformed into:
```
offsets: [0, 0], sizes: [8, 16], strides: [0, 1]
```
Note that outer offset of A can have any value as it's anyway multiplied with `strideA[0] == 0`.

[CombineStridedOps] Add case for size(A) > size(B)

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetCDODirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/bd_chaining.mlir

Adds support for a chain of DMA BD configurations with implicitly disabled locks:
```
^bb3:  // pred: ^bb5
%1 = aie.dma_start(S2MM, 1, ^bb4, ^bb2, repeat_count = 1)
^bb4:  // 2 preds: ^bb3, ^bb5
aie.use_lock(%lock_0_2, AcquireGreaterEqual, 1)
aie.dma_bd(%buf1 : memref<8x2x8x4xi32>) {bd_id = 1 : i32, len = 256 : i32, next_bd_id = 2 : i32}
aie.next_bd ^bb5
^bb5:  // 2 preds: ^bb4
aie.dma_bd(%buf1 : memref<8x2x8x4xi32>) {bd_id = 2 : i32, len = 256 : i32, next_bd_id = 1 : i32, offset = 256 : i32}
aie.use_lock(%lock_0_2_3, Release, 1)
aie.next_bd ^bb4
```
Here, there are two circular chained BDs (bd_id 1 calls bd_id 2 as next bd, which calls bd_id 1 again etc). In this case, the first BD only needs to acquire a lock and the second one needs to release one. The first BD will have its release …

[TargetCDO] Add support for implicit locks in BD chaining

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

This PR removed the pass that promotes the matmul output to local memory. We leave it to `comprehensive-bufferize` pass to handle the bufferization similar to what we did for elementwise ops with https://github.com/nod-ai/iree-amd-aie/blob/d4ed19b219c9aa6bc728924d08f8f4e82a04fb15/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp#L85.
This solves the redundant allocation and copy issue with a more complicated loop structures, e.g. https://github.com/nod-ai/iree-amd-aie/commit/168414bfb1235a2b21cc4c710e4aea81ddfba70e.

[Passes] Remove pass that promotes local output in pack-peel pipeline

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pack.mlir

Refactor `getOperandsFromDefOp` to search for and return `pack` ops up to a certain depth away from the linalg op's inputs and rename to `getPackOperands`. This enables more complex cases with intermediate `extract_slice` operations, see the new test cases being added.

[BufferizeToAllocation] Handle pack operands dependent on other op types

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir

To follow up on: https://github.com/nod-ai/iree-amd-aie/pull/972#discussion_r1876455187
cc @yzhang93

Refactor BufferizeOperand naming for clarity

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECombineStridedOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeLowering.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op_hardware_aware.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h

Some incorrect max size calculation in `DmaDimConfig` was blocking linear dimension folding and causing the following error when trying to increase the L1 matmul problem from 32x32x32 to 32x32x64 (MxNxK) for bf16:
```
<unknown>:0: error: 'aie.dma_bd' op Cannot give more than 3 dimensions for step sizes and wraps in this  tile (got 4 dimensions).
```
With this PR, that error should be resolved, but I am leaving the addition of that change to a separate PR. cc @yzhang93

Fix max sizes in DmaDimConfig and refactor

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseFillIntoForall.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_fill_into_forall.mlir

For 2x2 or 4x4 tiling the chain of ops after the fill looks like
```
%9 = linalg.fill ins(%cst : f32) ...
... 
%12 = scf.forall (%arg3, %arg4) in (2, 2) shared_outs(%arg5 = %9)  ...
...
%extracted_slice_19 = tensor.extract_slice %arg5 ... 
...
%19 = linalg.generic  ... outs(%extracted_slice_19 ... )
```
i.e. the filled value enters an extract_slice inside the scf.forall. But for 1x1 tiling, it looks like 
```
%9 = linalg.fill ins(%cst : f32)
...
%14 = scf.forall (%arg3, %arg4) in (1, 1) shared_outs(%arg5 = %9)
...
%19 = linalg.generic  ... outs(%arg5... )
```
i.e. there is no intermediate extract_slice. 
Before this PR, the logic was hardcoded to look for an extrac_slice, this PR relaxes this. 
Before this PR, 1x1 tiling hits https://github.com/nod-ai/iree-amd-aie/blob/f5ab91ebc3eb9fd7ffd8 …

[AMDAIEFuseFillIntoForall] Handle case where fill output is not sliced 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFusePackIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_pack_into_loop.mlir

This is very similar to https://github.com/nod-ai/iree-amd-aie/pull/976 
When the AIE grid we're using is `m x n` where one or both of `m` and `n` is `1`, for a matmul we get pack ops that produce operands for matmuls directly. i.e. as opposed to `pack->extract_slice->matmul` we have `pack->matmul`. 
TODO(newling) add a test and see if the pass can be simplified further.

[AMDAIEFusePackIntoLoop] Handle case where there is no extract_slice 

---

build_tools/ci/cpu_comparison/run.py

According to https://github.com/iree-org/iree/pull/9843, `iree-benchmark-module` only shows the latency for two digits after the decimal point. Set `us` as default.

[Tests] Add a time unit flag for performance runs

---

build_tools/ci/cpu_comparison/matmul_template/matmul_transpose_a_KxM_KxN.mlir
build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_air.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_generic.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

This PR only changes the lowering strategy for `matmul_transpose_a` ops. Changes for vectorization in `aievec` will be addressed in a separate PR.

[LoweringStrategy] Add support for matmul_transpose_a ops

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertLoopsForVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_loops_for_vectorization.mlir

With this PR, `mamtul_transpose_a` ops work with bf16->f32 vectorization. But i8->i32 tests don't work because of the following op
```
%10 = vector.transpose %9, [1, 0] : vector<8x4xi8> to vector<4x8xi8>
```
failed to lower to an `aievec.shuffle` op. 
https://github.com/nod-ai/iree-amd-aie/blob/befab5e1adb9a884d08f96bffb0b189f80f19aaa/compiler/plugins/target/AMD-AIE/aievec/VectorToAIEVecConversions.cpp#L244

Add vectorization support for matmul_transpose_a ops

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.h

Refactor `createDMA` and `convertSizeStrideToBDDimLayoutArrayAttr` to simplify the logic.

[LowerToAIE] Make DMA creation sizes and strides static as early as possible

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

Adds support for lowering `amdaie.npu.circular_dma_cpy_nd` to a chain of `aie.dma_bd` operations. This is needed becaused low-level DMA BD configurations currently don't support a  zero stride.
For example:
```
amdaie.npu.circular_dma_cpy_nd %some_connection([] [] [], [0, 0, 0] [2, 32, 32] [0, 64, 1])
```
contains an outer dimension with zero stride, which describes a repetition, and if this is not the common repetition count of all connections operating on a logical objectFifo, this is lowered to a chain of `dma_bd` operations to implement the zero stride:
```
^bb3:  // 2 preds: ^bb2, ^bb4
aie.use_lock(%lock_0_1_0, AcquireGreaterEqual, 1)
aie.dma_bd(%buffer_0_1 : memref<4096xi32, 1 : i32>) {dimensions = #aie<bd_dim_layout_array[<size = 32, stride = 64>, <size = 32, stride = 1>]>, len = …
```

[LowerToAIE] Add support for DMA chains

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseConsumerIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop.mlir

This PR adds support for iterative consumer fusion until no fusion opportunity can be found. See the test for an example in which this is needed: https://github.com/nod-ai/iree-amd-aie/compare/main...jtuyls:fuse-consumer-iters?expand=1#diff-df15abde86fbca464fa0a1e81b81bab2faaae00ea6a0aae73a9ba57477d78b05R471

[FuseConsumerIntoLoop] Add support for fusing iteratively

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESplitLogicalObjFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/split_logicalobjfifos.mlir

The old logic always split the outermost dimension of logical objectFifo to 1 without considering the number of Shim/MemTile used and could result in more channel usage than the limit. This PR modifies the splitting logic to depend on number of columns, so for example on a 4x2 AIE array, `amdaie.logicalobjectfifo<memref<4x1x32x32xi32, 1 : i32>>` will be split to two `amdaie.logicalobjectfifo<memref<2x1x32x32xi32, 1 : i32>>` .
This makes the e2e tests working for `numCols != numRows` cases.

[SplitLogicalObjectFifos] Modify the split factor to depend on num_cols

---

compiler/plugins/target/AMD-AIE/aie/test/unit_ctrl_routing.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.cc

This fix addresses an issue in the shim tile circuit flow for non-DMA/NOC ports. Previously, the router was producing incorrect connections in the generated switchbox configuration.
For a shim tile circuit flow defined as:
```ll
aie.flow(%t00, CTRL : 0, %t00, SOUTH : 0)
```
The router incorrectly generated:
```ll
aie.switchbox(%t00) {
aie.connect<SOUTH : 0, SOUTH : 0>
}
```
Instead, the correct output should be:
```ll
aie.switchbox(%t00) {
aie.connect<CTRL : 0, SOUTH : 0>
}
```
A new router unit test has been added to validate this behavior.

[Router] Fix shim tile connections for non-DMA/NOC ports

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESplitLogicalObjFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/split_logicalobjfifos.mlir

This PR add support for splitting logical objectFifos and DMAs with loop dependencies and a strided access specified through an affine expression. 
For example, if the data in a 4x4 objectFifo at some point is:
```
[0, 0, 0, 0]
[1, 1, 1, 1]
[2, 2, 2, 2]
[3, 3, 3, 3]
```
and for an `index` from 0 -> 2, two consumer DMAs access the following rows:
````
consumer 1: 2 * `index`  (thus rows 0 and 2) 
consumer 2: 2 * `index` + 1  (thus rows 1 and 3)
````
Then, the objectFifo is split into two objectFifos in the following way:
new objectFifo 1:
```
[0, 0, 0, 0]
[2, 2, 2, 2]
```
new objectFifo 2:
```
[1, 1, 1, 1]
[3, 3, 3, 3]
```

[SplitLogicalObjFifos] Support loop dependency and stride

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_generic.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

This PR enables outer permutation of the level 0 unpack, which results in a logical objectFifo with outer dimension aligning with the columns instead of rows. This helps with splitting and finding a routing solution after splitting (as we always split logical objectFifos on the outermost non-unit dimension). 
For example, when targeting strix with an 8 column array, this results in an output L2 objectFifo with shape `8x4x32x32` instead of `4x8x32x32`. Splitting therefore happens on the dimension with size 8 instead of size 4, which helps with assigning one output buffer to every column and finding enough channels for routing the data from L1 to L2.

[KernelDispatch] Enable unpack outer permutation for (batch)matmul

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELinalgFunctionOutlining.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/linalg_function_outlining.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/linalg_function_outlining_to_empty.mlir

This PR has an experiment that checks how much performance loss is due to compute vs data movement.  It does the following: it adds an option to elide/omit the computation of the outlined function entirely, basically replacing the matmul with a noop. This gives us a lower bound answer to the question: how fast would we be if the kernel running on the AIE core was 100% efficient? Scraping the result from CI (see c&ps below) we see that replacing the matmul with a noop goes from 1932 us to 1859 us -- a 4% speedup. So the actual speed-up we'd get from a 100% efficient kernel is in range 0% - 4%. i.e. not very much. 
With matmul:
```
matmul_benchmark_4096_512_512_bf16_f32_O3_outline.mlir
-------------------------------------------------------------------------------------------------- …
```

[Benchmarking option] Make outlined functions do no compute

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_air.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_generic.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

Permutes the level 0 RHS pack operations to always get RHS/B on L2 into the packed layout [N K ? ?] instead of [K N ? ?]. This is needed for splitting on the outer dimension when caching more of K in L2 (K > 1).

[KernelDispatch] Add matmul RHS outer permutation

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIERT.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIERT.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetCDODirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt

The following interface functions between the `xilinx::aie` dialect and `aie-rt` have been relocated and renamed
`Target/AMDAIETargetCDODirect.cpp/addAieElfsToCDO` ->`Target/AMDAIERT.cpp/addAllAieElfs`
`Target/AMDAIETargetCDODirect.cpp/addCoreEnableToCDO` -> `Target/AMDAIERT.cpp/addAllCoreEnable`
`Target/AMDAIETargetCDODirect.cpp/addInitConfigToCDO` -> `Target/AMDAIERT.cpp/addInitConfig`
The motivation is, these functions are not specific to the CDO and can be useful in other contexts, such as generating control packets.
Brief documentation has also been added for these functions in the new header file.
related: https://github.com/Xilinx/mlir-aie/pull/1760

[TargetCDODirect] Separate aie-rt related functions into a new library

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_convolution_using_scf_forall.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_matmul_using_scf_forall.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.cc
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h

Adds a new pipeline with an additional level of tiling for matmul-like operations on the outer dimension. This should reduce the DDR BW requirements by caching more data slices on L2/MemTile.

Add new pack-peel pipeline with 4 tiling levels

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignTiles.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_tiles.mlir

-- This commit changes ValueRange -> SmallVector<Value> for single row
multi column non-local buffer's tile assignment.
Signed-off-by: Ian Wood <ianwood2024@u.northwestern.edu>

[AssignTiles] Fix ValueRange -> SmallVector<Value> for storing tiles

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir

Makes IR easier to mentally parse -- it should be easier to figure out which columns/rows a ` LogicalObjectFifoFromMemrefOp` is on. 
```
%lof_3_2 = ... // column 3, row 2
%lof_3_r = ... // column 3, multiple rows or unkown row 
```
The lit tests have more examples

[IR] Pretty-printer for LogicalObjectFifoFromMemrefOp

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir

Will now be `%tile_c_3` and `%tile_2_r` if one or other of the column and row are integers. As opposed to just `%tile` and `%tile_1`. This aligns tile printing with the (not landed) printing of logicalobjectfifos: https://github.com/nod-ai/iree-amd-aie/pull/1017

[IR] Update how tile's with partial info are printed 

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseConsumerIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop.mlir

This PR extends the consumer fusion to work for matmul + elemwise in case of an additional level of tiling (see added lit test).

[FuseConsumerIntoLoop] Extend to multiple results and generalize depth fusion

---

runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/bo.cpp

Hi mates, 
During the build process with the below-mentioned CMake instructions, I encountered an error in the XRT-LITE HAL codes. The errors are many due to missing parentheses in some of its comparison operations and I also included the error for the reference. 
Regards 
Vimal
Error:
```
error: suggest parentheses around ‘-’ in operand of ‘&’ [-Werror=parentheses]
```
CMake:
```
cmake \
-B <WHERE_YOU_WOULD_LIKE_TO_BUILD> \
-S third_party/iree \
-DIREE_CMAKE_PLUGIN_PATHS=$PWD \
-DIREE_BUILD_PYTHON_BINDINGS=ON \
-DIREE_INPUT_STABLEHLO=OFF \
-DIREE_INPUT_TORCH=OFF \
-DIREE_INPUT_TOSA=OFF \
-DIREE_HAL_DRIVER_DEFAULTS=OFF \
-DIREE_TARGET_BACKEND_DEFAULTS=OFF \
-DIREE_TARGET_BACKEND_LLVM_CPU=ON \
-DIREE_BUILD_TESTS=ON \
-DIREE_EXTERNAL_HAL_DRIVERS=xrt-lite \ …
```

Added Parentheses Around Some Comparison Operations

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertCoreForallToFor.cpp

This fixes the error 
```
error: 'amdaie.core' op failed to coalesce for loops
```
in the test 
```
MatmulTransposeB(
128,
256,
128,
"i8",
"i32",
tile_pipeline="pack-peel-4-level-tiling"
)
```
The source of error is some very defensive code in MLIR: https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SCF/Utils/Utils.cpp#L903 (Why shouldn't I do a no-op coalesce of 1 for op?). 
Note: compilation gets further with this fix, but doesn't compile to completion

Compilation error fix for matmul transpose B with pack-peel-4-level-tiling pipeline

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECombineStridedOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir

This PR generalizes dimension checking in `CombineStridedOps`. This allows difference ops to provide their own dimension checking implementation. This is needed because circular and non-circular `dma_cpy_nd` ops have different logic for checking whether the number of dimensions of the combined DMA op would exceed the available number of dimensions.
With this fix, BatchMatmul works with the `pack-peel-4-level-tiling` pipeline.

[CombineStridedOps] Generalize dimension checking

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/split_logicalobjfifos.mlir

-- We anyway use gcd for computing splitFactor when split factor has
not been explicitly provided/computed. But we error out if the
provided split factor doesn't divide source/target size.
-- This commit therefore allows replacing the explicitly provided
split factor with gcd when the former doesn't divide source/target
size.

[SplitLogicalObjFifo] Allow using gcd for computing splitFactor

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pack_or_copy.mlir

The defining ops of the inputs of computation op can be copy or pack ops. This PR extends the support to cover the copy ops given depth to the computational op.

[BufferizeToAllocation] Add support to bufferize linalg.copy ops given input depth

---

.github/workflows/ci-linux.yml
build_tools/ci/cpu_comparison/performance_publish.py
build_tools/ci/cpu_comparison/performance_summarizer.py

The workflow: 
- run performance benchmarks the same way as before, generating `performance.log`
- convert `performance.log` into `results.json`
- switch to the `gh-pages` branch
- append the new  `results.json` data to `results_history.json`
- create `results_history.html` based on the updated `results_history.json`
(only when CI is triggered from the `main` branch)
- commit the updated `results_history.json` and `results_history.html` using the action bot
To preview what it looks like: [https://rawcdn.githack.com/nod-ai/iree-amd-aie/a70ddbeea9d0b0d14f8ab24208efc599bc3c2f39/results_history.html](https://rawcdn.githack.com/nod-ai/iree-amd-aie/a70ddbeea9d0b0d14f8ab24208efc599bc3c2f39/results_history.html)
I don’t have access to set up the webpage for this repository, but once the …

[CI] Track performance numbers on a webpage

---

build_tools/ci/cpu_comparison/run.py

The batch_matmul tests with the pack-peel-4-level-tiling pipeline result in intermittent numerics issues, making the CI unstable. I was able to reproduce this offline and will need to investigate this further.

Disable failing batch_matmul tests

---

build_tools/ci/run_matmul_test.sh

Locally, on a Strix machine, I have been able to crash the NPU in turbo mode, requiring a cold reboot. I am not sure that this is the same issue as we're occasionally seeing with the CI runners, but the result is similar, and I think it's worth a try disabling these tests for a while to verify.

[CI] Disable turbo mode tests due to instability

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECombineStridedOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/combine_strided_ops.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_composition.mlir

- slight modification to logic used for compositing DMAs, makes use of global offset difference (please see comments in code)
- more aggressive folding of unit dimensions 
- new unit test in combine_strided_ops.mlir shows the case that was being missed in an end-to-end matmul transpose b with the new pipeline pack-peel-4-level-tiling

[DmaComposition] Rework logic to enable new composition opportunity

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/invalid.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEGenerateControlOverlay.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/generate_control_overlay.mlir

Instead of generating `flow` operations, we now directly insert `connection` operations into the overlay. The motivation behind this change is that these `connection` operations will be useful for generating control packet DMAs in subsequent steps.

[CtrlPkt] Generate `connection` operations in the overlay

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

This is a fix for the compilation error
```
<unknown>:0: error: 'amdaie.npu.circular_dma_cpy_nd' op could not fold repetition counts
```
that is observed some transposed matmuls with the new pack-peel pipeline. What was happening was that the `lower-to-aie` pass is assumed a stride-0 leading dimension was always or never present, but that wasn't the case

[LowerToAIE] fix for `op could not fold repetition counts`

---

build_tools/ci/cpu_comparison/run.py

-- This commit adds larger shape e2e bfp16 Ukernel test to CI for
both pack-peel as well as pack-peel-4-level-tiling targeting
4x8 array on Strix.

[CI] Add larger shape e2e bfp16 Ukernel test

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELinalgFunctionOutlining.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/disable_linalg_function_outlining.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/linalg_function_outlining.mlir

To avoid overheads of non-outlined ops when using `outlining=true` with `--iree-amdaie-replace-outlined-functions-with-empty`, I think there should be an option to outline all ops if needed, so I created three outlining strategies:
- None: no outlining.
- All: outline all ops.
- Balanced (default): this is the same as what happens in main currently, outlining some ops and not others for a tradeoff in performance and program size.

[LinalgFunctionOutlining] Add none, all and balanced outlining strategies

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu4.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESplitLogicalObjFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/split_logicalobjfifos.mlir

In order to decide the split factor we were basing the inference solely on the number of columns available.
Because of this, for 4x8 array and for the new pipeline, we were splitting L2 buffers :-
1. LHS - 8 times.
2. RHS - 8 times.
3. OUT - 8 times.
As a result, the tiles being assigned were :-
1. LHS : (0,0) -> (7,0)
2. RHS : (0,0) -> (7,0)
3. OUT : (0,0) -> (7,0)
This causes exhaustion of DMA channels. Refer to [this](https://github.com/nod-ai/iree-amd-aie/pull/1031#discussion_r1920237380) thread for the discussion thread.
The L2 buffer split should be :-
1. LHS : (0,0) -> (3,0)
2. RHS : (0,0) -> (7,0)
3. OUT : (0,0) -> (7,0)
So that later on when the tiles are being assigned, the expected no. of tile assignments for LHS/RHS/OUT matches the corresponding L2 buffers.
This PR aims to …

[SplitLogicalObjFifo] Fix split-logicalobjfifo pass to analyse unique producers/consumers ObjFifos

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op.mlir

Add support for folding linear dimensions with non-zero, but static, offsets. For example:
```
Offsets: [8, 0], Size: [16, 8],  Strides: [8, 1]
```
can now be transformed into:
```
Offsets: [64], Size: [128],  Strides: [1]
```

[FoldLinearDims] Support folding with static non-zero offsets

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignTiles.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Transforms.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEOpUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_tiles.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

This PR refactors the `AMDAIEAssignTiles` pass to prepare for adding more complex tile assignment strategies to make effective use of the available memory. This PR on purpose doesn't make any (major) change in how the tile assignment happens currently.

[AssignTiles] Refactor pass to make it more extensible

---

.github/workflows/ci-linux.yml

Disable reset_npu in `E2E comparison of AIE to llvm-cpu` on Phoenix runner, but still keep it in the `Performance` session. We'll see if it solves the crash issue.

[CI] Disable reset_npu in phoenix e2e test

---

build_tools/ci/cpu_comparison/run.py

Currently, there are Matmul/MatmulTranspseB/MatmulTransposeA classes and their Benchmark classes separately. A lot of codes are duplicated between them. This also brings extra efforts and more codes if we introduce other classes, e.g., mmt4d.
This PR removes the Benchmark classes while adding an argument "run_benchmark" to the existing Matmul/MatmulTranspseB/MatmulTransposeA classes.

[CI] Merge Matmul class with its Benchmark class

---

build_tools/ci/cpu_comparison/run.py

-- Currently there are lot of repeated codes which makes :-
1. Maintaining the codebase
2. Addition of new tests,
quite cumbersome.
-- Since most tests are bound to go through a certain lowering pipeline,
decide whether or not to use ukernel, chess, have additional compilation
flags - it's better to separate those as RunningParams instances.
-- This way they're handled unanimously at the base class instead of each
subclass taking the same onus.
-- This can further be refined but for now going ahead with the current
design.

[e2e CI] Refactor e2e CI tests to make addition of new tests easier

---

build_tools/ci/cpu_comparison/run.py

-- This commit adds e2e Batchmatmul CI test for Strix targeting 4x8
array and pack-peel-4-level-tiling. Since the numerical inconsistency
has been known to be on Phoenix, it adds `n_repeats=10` for each of
the new tests added.
-- Currently only for i32->i32 the tests are added as the vectorization
support for bf16->f32 is not enabled for Strix.

[e2e CI] Add Strix Batchmatmul - pack-peel-4-level-tiling - i32->i32 - 4x8

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu4_peano.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/AMDAIEXCLBinGenTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/aie_elf_files_gen_test.cpp
runtime/src/iree-amd-aie/driver/xrt-lite/cts/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/cts/CMakeLists.txt
tests/conftest.py

Adds a path to compile ukernels through peano. The compilation time is a lot faster this way, potentially at a decrease in performance, but potentially ukernels could be written in a way that enables good performance via peano as well.

[UKernel] Add ukernel to be compiled through peano

---

build_tools/ci/cpu_comparison/matmul_template/matmul_trunci_MxK_KxN.mlir
build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu1.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu4.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_cores.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/vectorization.mlir

Add support for handling Matmul + Trunci : i8->i8 on Phoenix/Strix.
On Phoenix it works via both vectorization as well as ukernel path.
On Strix it currently works only via ukernel path.
Therefore, for now, three e2e CI tests have been added.

 [Pack-peel-4-level-tiling] Enable Matmul+Trunci : i8->i8 on Phoenix|Strix + Ukernel|Vectorization

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

This removes explicit checks for Vitis/chess and allows compiling and running an e2e test with ukernels with just peano installed.

Remove checks for Vitis when targeting ukernels

---

build_tools/ci/cpu_comparison/matmul_template/matmul_generator.py
build_tools/ci/cpu_comparison/matmul_template/matmul_trunci_scaling_MxK_KxN.mlir
build_tools/ci/cpu_comparison/run.py

-- This commit adds e2e CI tests for Matmul+Trunci with scaling.
-- In an actual quantized model, truncating from a higher bitwidth to a lower precision bitwidth 
won't work and we need to scale.
-- Since the output of the Matmul here is an integer cannot be multiplied with a floating point
scale factor, we need to represent the scale factor with a multiplier and a shift operator instead.
-- Eg: a float scale factor of 0.333 could become multiply by 357913941 and shift right 30.

[e2e CI] Add e2e CI tests for Matmul+Trunci with scaling

---

build_tools/ci/cpu_comparison/run.py

Without this, if no vitis directory path is specified, the non-ukernel peano tests do not run. 
aka: System alert: dangerously high entropy level detected!

[CI] Relax gating on when tests are skipped

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignChannels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEGenerateControlOverlay.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_channels.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/generate_control_overlay.mlir
runtime/src/iree-amd-aie/aie_runtime/Utils/CMakeLists.txt
runtime/src/iree-amd-aie/aie_runtime/Utils/ChannelGenerator.cpp
runtime/src/iree-amd-aie/aie_runtime/Utils/ChannelGenerator.h
runtime/src/iree-amd-aie/aie_runtime/Utils/test/ChannelGeneratorTest.cpp

Changes in this PR:
- Previously, channels for data flows were assigned first using the `AssignChannels` pass, followed by control flow channel assignment with the `GenerateControlOverla`y pass. This PR reverses the order, ensuring that control flow channels are assigned before data flow channels.
- Previously, in the runtime `ChannelGenerator`, packet flow channels were not explicitly marked as assigned (so that they can be reused), while only circuit flow channels were tracked. However, this could result in a packet flow channel later being mistakenly reused by another circuit flow.  Now, both circuit and packet flows track their assigned channels and store them separately. This ensures that circuit flow channels remain exclusive, while packet flow channels can be reused but only by …

[AssignChannels] Prioritize channel assignment for control packets 

---

compiler/plugins/target/AMD-AIE/aie/AMDAIECoreToStandard.cpp
compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/aie/test/lower_buffer.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIESinkIntoCore.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/sink_into_core.mlir

This is part of the PR to vectorize linalg.fill: https://github.com/nod-ai/iree-amd-aie/pull/1095
Basically one of the patterns introduced in https://github.com/nod-ai/iree-amd-aie/pull/1095 means that in one of the subsequent passes (lowering to llvm dialect) a cast operation is introduced outside of an aie.core, which needs to be inside the aie.core for core-to-standard to work.  i.e. we need to sink an operation into an aie.core. Before this PR, there is already a pass to sink operations into `amdaie.core`. This PR refactors that pass so that it can be reused to sink into `aie.core` (or any other regioned op).

[AMDAIESinkIntoCore] Generalize sinking for reuse with other regioned ops 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp

I am working on adding additional patterns to be recognized and replaced with ukernels (scale + trunc), so refactoring the `LowerToUKernels` pass to make that more easy to do. Added some additional small improvements along the way like replacing `failure` with `rewriter.notifyMatchFailure`, using explicit types, reordering some statements etc.

[LowerToUKernels] Refactor to simplify and improve extensibility

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/AMDAIEXCLBinGenTest.cpp

This will replace https://github.com/nod-ai/iree-amd-aie/pull/1116 -- instead of string matching the assembly file, it uses llvm's `llvm-readelf` after adding `--stack-size-section` to the llc call.

Function to estimate stack size (using existing tooling)

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/aievec/test/canonicalize_transfer_write_for_load.mlir
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/vectorization.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h

This PR contains multiple changes to get vectorized assembly through peano, I will split it into multiple PRs. 
Eyeballing the first test in the performance benchmark:
Before:
```
matmul_512_512_4096_bf16_f32_O2_npu1_4col_benchmark
--------------------------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------------
BM_matmul/process_time/real_time_mean         2673 us         66.3 us            5 items_per_second=374.194/s
BM_matmul/process_time/real_time_median       2668 us         63.1 us            5 items_per_second=374.766/s
BM_matmul/process_time/real_time_stddev       19.3 …
```

Vectorization of linalg.fill 

---

compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/aievec/test/precanonicalization-aieml-llvmir.mlir

As with `arith.truncf` and `trunci`, this pattern is useful when lowering other ops.

[AIEVec] additional flattening of arith ops 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/aie2xclbin_test.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/aie_elf_files_gen_test.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/ctrlpkt_gen.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeLowering.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertDeviceToControlPackets.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEGenerateControlOverlay.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/controlcode_lowering_ctrlpkt.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/convert_device_to_control_packets.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/generate_control_overlay.mlir

This PR implements a pipeline in `XCLBinGen` for the generation and conversion of control packets. The `aie.device` is converted into `ctrlpkt_sequence.txt` and `ctrlpkt_instructions.txt`, which store the contents and instructions for control packet DMAs, respectively. These files will later be used by the driver to perform the reconfiguration.
Changes related to the driver and a new on-device test will be submitted in follow-up PRs.

[CtrlPkt] Add pipeline to dump control packet binaries to files

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Now
```
An upper bound for the stack size of the core (col=0, row=2), inferred from the object file, is 1448 bytes. The assigned memory for the stack is 1024 bytes, which is insufficient (1448 > 1024).
```

Fix typos in error message when insufficient stack size 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeToTransaction.cpp

This PR fixes a bug introduced by #1002, where the instruction count printing was incorrect because it occurred before resizing the instructions vector. The logging is now moved inside `finalizeAndReturnInstructions` after `instructions.resize(instructionCount)`, ensuring the correct count is printed instead of zero.

[ControlCodeToTransaction] Fix controlcode size printing

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECanonicalizeDoublyStridedOp.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEDmaUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEDmaUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/canonicalize_doubly_strided_op_hardware_aware.mlir

This PR adds a dimension expansion rewrite to the doubly-strided op canonicalizer, which is effectively the reverse of the `FoldDmaOpLinearDims` transformation. This fixes: #1137 (see test being added).
Example:
```
offsets: [0], sizes: [8], strides: [1], maxSizes: [5]
```
is expanded into:
```
offsets: [0, 0], sizes: [2, 4], strides: [4, 1]
```
Here, all the sizes are smaller or equal to the max size. This helps with enabling more DMA composition transformations, and this is needed to avoid nested `npu.circular_dma_cpy_nd` ops after `DmaComposition`, which is why it fixes #1137. Note that we should probably add some checks that all `npu.circular_dma_cpy_nd`  ops are combined and subsumed correctly to help with debugging issues. I will address that in a follow-up.

[CanonicalizeDoublyStridedOp] Add expansion of dimensions exceeding max sizes

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/AMDAIEXCLBinGenTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_fill_into_forall.mlir

This PR extends the aie-opt pipeline with Common Subexpression Elimination (CSE) to achieve better scalar arithmetic without increasing Program Memory (PM) usage.
Background:
- Currently, -O3 optimization provides better performance than -O2  (function outlining, phoenix, and matmul). 
- However, -O3 significantly increases program memory usage compared to -O2.
- The performance improvement in -O3 is largely due to unintended effects of function inlining, which rearranges integer arithmetic and reduces common subexpressions.
Problem:
- In -O2, the outlined function after optimization contains redundant operations, e.g.:
%45 = trunc i64 %38 to i20
...
%49 = trunc i64 %38 to i20
- -O3 eliminates these redundancies indirectly through inlining, but at the cost of increased memory usage. …

Add CSE to aie-opt pipeline to improve -O2 performance

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Test/samples/matmul_pack_peel_objectfifo_ukernel_e2e.mlir

I expect/hope the C++ code will use defaults if not provided
My guess is that we need to update the default for strix, might not be 8 columns 
UPDATE:
My guess was wrong. The issue was related to this: https://github.com/nod-ai/iree-amd-aie/pull/955#discussion_r1870234195
The default number of rows and columns wasn't based on the provided device, it was based on the default device! I suggested this to Vivian (see above), but in retrospect I don't think it was a good design choice. In this PR I've improved it, so that the default number of rows and columns is just 'all', where the actual number is determined after the device is known.

Do not explicitly use `--iree-amdaie-num-rows` if it is default 

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEAssignBufferAddresses.cpp

Remove the unnecessary warning to be less noisy in ci.

[AssignBufferAddresses] Remove warning

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertDmaBdChain.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_dma_bd_chain.mlir

Similar to #1157, enabling another optimization that slightly improves the performance.
|                       | Latency(us) | Instructions |
|-----------------------|-------------|--------------|
| circuit               | 2695        | 1096         |
| packet before this PR | 41879      | 503748       |
| packet after this PR  | 40761       | 503176       |

[InsertDmaBdChain] Enable BD chain optimization for packet flows

---

build_tools/ci/cpu_comparison/run.py
build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignConnectionTypes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_connection_types.mlir

The DMA loop subsumption optimization is crucial for unlocking packet flow performance.
Without  loop subsumption:
```ll
for i = 0 to 16
dma_cpy arg_0[i]
dma_cpy arg_1[i]
sync
```
When unrolled, this generates a large number of DMA operations in the control code.
However, with loop subsumption:
```ll
dma_cpy arg_0
dma_cpy arg_1
sync
```
Here, the loops are absorbed by strides in `dma_cpy`, significantly reducing control code size.
However, enabling this optimization for packet flows may introduce deadlocks if `arg_0` and `arg_1` share an arbiter at any point along their routed path.  Since arbitration order is not guaranteed, a deadlock can occur if two tiles of `arg_0` are sent from shim, but zero tiles of `arg_1`, while the core is waiting for `arg_1` before accepting the second tile of …

[PktFlow] Disable packet flows on kernel output to allow loop subsumption

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPad.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pad.mlir

Before this PR, if we use pad operation for data movement, only the operands from root computation op were padded/copied. However, for matmul-elementwise dispatch, we want to generate copies for the matmul inputs and elementwise output but not matmul output or elementwise input.
This PR adds option `pad-elementwise` to deal with matmul and elementwise operations separately. In addition, it removes option `padding-level`, instead use a more direct name `pad-operand` to be clear about what operands are padded. These option settings and logic of applying them are similar to [BufferizeToAllocationPass](https://github.com/nod-ai/iree-amd-aie/blob/b569da497fba0c2840bae42fd0c3bb8380c4953f/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp#L166).
This is a fix …

[AMDAIEPad] Refactor the pass to pad elementwise op

---

build_tools/ci/cpu_comparison/matmul_template/matmul4d_trunci_scaling.mlir
build_tools/ci/cpu_comparison/run.py

This PR adds an example test for `matmul4d + scaled_trunci` ops. 
- Since currently the upstream IREE doesn't support the transposed matmul and elementwise ops to be fused in a single dispatch, we manually add these ops to `flow.dispatch.region`.
- Currently, the performance for `matmul4d + trunci` is much worse than `matmul4d i8->i32` alone, mostly likely due to the elementwise ops are scalarized instead of vectorized.

Add performance test for Matmul4d + Trunci

---

build_tools/ci/cpu_comparison/matmul_template/matmul4d_trunci_scaling.mlir
build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu4_peano.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

This PR adds a ukernel for performing shift + truncation from i32 to i8 and updates the `matmul4d_trunci_scaling` test to use this ukernel. This should improve performance by +- 20% compared with the same matmul test without truncation (i32 output). The new best number is 360us now for truncation to i8, compared with 490us for just i32:
```
matmul4d_512_4096_512_i8_i32_O3_npu4_outline_4_level_tiling_ukernel_chess_benchmark
----------------------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------
BM_matmul4d/process_time/real_time_mean          490 us         28.9 …
```

[UKernel] Add shift and trunc ukernel

---

build_tools/ci/cpu_comparison/run.py
runtime/src/iree-amd-aie/driver/xrt-lite/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt-lite/executable.cc
runtime/src/iree-amd-aie/driver/xrt-lite/executable.h

This PR adds support for reconfiguration time measurement, with results being logged on the performance tracking webpage once merged:
https://nod-ai.github.io/iree-amd-aie/results_history_npu1.html
Observations on my local machine: The current reconfiguration time for the whole array is quite poor (~110ms), whereas the ideal target is < 100µs. After discussing with @jtuyls, the top optimization priority should be reducing the control code size for control packet DMAs.
Note: Due to the current bad performance, this newly added benchmark test will increase phoenix CI time by ~10s, but this should get optimized soon.

[CI] Add benchmark test for reconfiguration time measurement

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEAssignBufferAddresses.cpp
compiler/plugins/target/AMD-AIE/aie/test/bank_aware_buffer_alloc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h

Sorting the buffer by largest allocation and assigning those larger buffers first would help for better bank assignment and avoid conflicts. However, this was disabled previously because `depthwise_conv2d` op had numerical error after sorting. I haven't found the reason behind that and couldn't find a better solution. This PR temporarily disable the bank-aware scheme for conv ops as I continue looking into the [issue](https://github.com/nod-ai/iree-amd-aie/issues/1192) for depthwise ops.

[AssignBufferAddresses] Enable buffer sorting and disable bank-aware scheme for Conv

---

compiler/plugins/target/AMD-AIE/aie/AIEX.td
compiler/plugins/target/AMD-AIE/aie/test/aiert_insts.mlir
compiler/plugins/target/AMD-AIE/aie/test/dma_to_npu.mlir
compiler/plugins/target/AMD-AIE/aie/test/dma_to_npu_issue_token.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/bd_chaining.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_16x16_8xi32__dispatch_0_matmul_16x1_0.aiecc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_16x64_32xi8__dispatch_0_matmul_tran_0.aiecc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_512x512_512xi32__dispatch_0_matmul__0.aiecc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_64x64_64xbf16__dispatch_0_matmul_64_0.aiecc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_64x64_64xi8__dispatch_0_matmul_64x6_0.aiecc.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/test/matmul_8x32_16xi32__dispatch_0_matmul_8x32_0.aiecc.mlir

- Remove more assertions to potentially fix the random CI failures.

Bump mlir-air to e19dd32108a1d55132bbc115384dc493e3126af4

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseProducerIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_producer_into_loop.mlir

To be merged after https://github.com/nod-ai/iree-amd-aie/pull/1189
- This commit adds a fix for materializing the operand of the compute
op inside `iree-amdaie-fuse-producer-into-loop`.
-- Whenever the defining op of an operand is a linalg.pack/copy and is
not defined in the same block, we simply move that inside the block.
-- Else we try to find a tensor.extract_slice through the use-def chain
and tile/fuse it.
-- This makes 32x32x128 i32->i32 work on 1x1 for `pack-peel-4-level-tiling`.

[FuseProducerIntoLoop] Fix materializing the operand

---

build_tools/ci/cpu_comparison/matmul_test_config.py
build_tools/ci/cpu_comparison/run.py

-- This commit refactors e2e CI Matmul tests to :-
i.  Enable streamlined addition of new tests
ii. Track all test configs for Phoenix vs Strix.
NOTE: Take a look at [these two tests](https://github.com/nod-ai/iree-amd-aie/blob/d68ec8b21a6b8bfa184825891d796f2fe6539ba9/build_tools/ci/cpu_comparison/run.py#L2099-L2129) which are in `main`- they're simply duplicates and are not checking anything different. By this refactor the goal is to ensure whenever we're adding new tests in the config file we do so based on the number of cores as well as in increasing order of shapes. This way there's lesser chance of test duplication as well as easier to track the config.

[NFC][e2e CI] Refactor e2e CI Matmul tests

---

build_tools/ci/cpu_comparison/matmul_test_config.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIELogicalObjFifoSplittingUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/split_logicalobjfifos.mlir

-- This commit adds a fix in `iree-amdaie-split-logicalobjfifo` to address those case when there's no splitting of a logicalobjfifo and the producer/consumer DMAs have affine.apply in offset at the inferred splitting dimension.
NOTE: Although I've added an e2e test but since strix machine is currently not accessible, the only thing verified is the compilation. Without the fix that this PR is trying to add, `32 x 32 256` for `1x1` for `pack-peel-4-level-tiling` on Strix leads to a compilation failure wherein `amdaie.connection` op ends up having multiple users. This was happening because `DMAComposition` failed to combine the strided ops, which in turn was happening because of incorrect offset on the L2 buffer in L2->L1 DMACpyNd.
Here is the …

[SplitLogicalObjFifo] Add fix for new offset in case of no splits

---

.github/workflows/ci-windows.yml

During the compilation process, some log files are dumped to the system temp directory by default. 
https://github.com/nod-ai/iree-amd-aie/blob/357698b70dd329239cbf7d2c28e2683560972c2a/compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp#L564
However, on Windows machines, this directory is not automatically cleaned up, leading to accumulated files that can cause CI failures or significantly slow down runs.

[CI] Clean up Windows temp files older than 30 days

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignTiles.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Transforms.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_tiles.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_air.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.cc
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h

This PR increases the usage of L2 memory by increasing the L2 tile sizes within memory bounds and by improving the algorithm to assign logical objectFifos across tiles. This updated algorithm now assigns larger logical objectFifos first and takes into account the actual memory usage on tiles, with leads to better usage of available memory.

[AssignTiles] Update algo to take into account tile memory limitations

---

runtime/src/iree-amd-aie/driver/xrt-lite/device.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc

`iree_hal_xrt_lite_device_queue_execute` always executes with an empty `binding_table`, which breaks kernel argument passing. This change would fix it.

[Driver] Fix propagating binding_table

---

build_tools/ci/cpu_comparison/run.py

This PR fixes the placement of logging for operation count, number of rows, and number of columns in the test script. According to the parser logic in [performance_summarizer.py](https://github.com/nod-ai/iree-amd-aie/blob/5cfbf5cb0d1593dc3dc1a82d9122c36c9f81d7e1/build_tools/ci/cpu_comparison/performance_summarizer.py#L66-L68), these values should be printed after the `Performance benchmark:` line. Otherwise, it could cause `json_summary["tests"][-1]` to point to the wrong entry.

[CI] Fix operation count logging in test script

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h

-- This commit adds API to fetch max repeat count and uses that to bail
out on loop subsumption for non-circular DmaCpyNd ops where the total
loop iteration count is greater than the max repeat count.

[DmaLoopSubsumption] Account for max repeat count for NpuDmaCpyNd

---

build_tools/ci/cpu_comparison/run.py

The test is randomly failing on both main and PRs.

[CI] Disable `three_matmuls` test

---

build_tools/ci/cpu_comparison/run.py

Adds back the 1024x16384x512 matmul benchmark through peano to compare with chess to check whether it passes CI. Will follow up with another PR to improve the ukernel performance.

Add 1024x16384x512 matmul bench with peano ukernel

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlPacketToNpuDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFoldDmaWaits.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertDmaBdChain.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fold_dma_waits.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_dma_bd_chain.mlir

Follow-up to #1210 and #1243.
This PR introduces a new  `barrier` op to provide finer-grained control over the ordering of control packets.
It serves as an optimization boundary, preventing any DMA wait/sync optimizations (such as folding or chaining) from crossing it. 
Currently, the barrier is heuristically set when control packets switch between destination tile types.

[CtrlPkt] Fix `three_matmuls` test

---

build_tools/ci/cpu_comparison/matmul_test_config.py
build_tools/ci/cpu_comparison/performance_publish.py
build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/aie/AMDAIECreatePathFindFlows.cpp
compiler/plugins/target/AMD-AIE/aie/Passes.td
compiler/plugins/target/AMD-AIE/aie/test/test_create_packet_flows2.mlir
compiler/plugins/target/AMD-AIE/aie/test/test_create_packet_flows3.mlir

Depends on #1248.
This PR updates most tests in the python script to use control packets and also packet flows by default, except:
- air pipeline tests: due to missing passes related to control packets
- convolution tests + two strix matmul tests: due to the deadlock issue described in #1148

[CI] Enable control packets by default

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignChannels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_channels.mlir

Due to the round-robin assignment mode for packet flows, they attempt to utilize all available channels for load balancing. Therefore, they should be assigned only after circuit flows. Note that this change does not affect control flows, as their channels are pre-assigned in a separate pass ([GenerateControlOverlay](https://github.com/nod-ai/iree-amd-aie/blob/8546f47d34c62ca9b2f796b192f06b901141834d/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEGenerateControlOverlay.cpp#L67)).

[AssignChannels] Prioritize circuit over packet connections

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEAssignBufferAddresses.cpp
compiler/plugins/target/AMD-AIE/aie/test/bank_aware_buffer_alloc.mlir

This PR mainly contains two improvements:
1. Switch different schemes per tile, so if a particular tile failed on `bank-aware` scheme, it will fall back to the `sequential` scheme but not affect any buffer in other tiles.
2. For large buffers that cannot fit in a single bank, it will try to allocate a group of contiguous banks and avoid bank conflicts.

[AssignBufferAddresses] Improve bank-aware scheme to support large  buffer across multiple contiguous banks

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/aie/AIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToAIE.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_aie.mlir

This is needed to start enabling O2 in the peano ukernel compilation as the stack size needs increase. This doesn't enable O2 yet by default as that results in out-of-program memory issues in other tests, so leaving that to a follow up.

Add flag to specify stack size to be allocated in AIE cores

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEAssignBufferAddresses.cpp

This PR addresses the remaining comments in https://github.com/nod-ai/iree-amd-aie/pull/1256#discussion_r2079892859.

[NFC][AssignBufferAddresses] Use `BankStates` struct for unified bank metadata

---

.github/workflows/ci-linux.yml

This PR updates the CI workflow to skip the Performance (benchmark) tests during the `E2E comparison of AIE to llvm-cpu` step on Strix. The corresponding numerical correctness tests will still run as expected.
No changes are needed for Phoenix tests, as the `--skip_tests` flag is already set correctly for them.

[CI] Do not run benchmark tests twice on strix

---

build_tools/ci/cpu_comparison/matmul_test_config.py
build_tools/ci/cpu_comparison/run.py

Removes most chess tests on Strix, except one for benchmarking, to bring down CI time. Leaves them on Phoenix for now.

[CI] Remove Strix chess tests except one for benchmarking

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignNpuDmaBdIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_npu_dma_bd_ids.mlir

-- This commit updates `iree-amdaie-npu-dma-bd-ids` pass to ensure
equal distribution of BD IDs amongst DMAs within same scf.for block and
operating on same tile.
-- This fixes the issue of misalignment of DMA ops which causes issues
further down the stack in `insert-dma-chain` optimization pass.

[AssignNpuDmaBdIds] Equally distribute BD IDs amongst DMAs in same scf.for block/tile

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Enabling O2 by default for compiling peano ukernels on all tests in CI needs following changes:
- Avoid out-of-memory errors (program memory)  by adding `-ffunction-sections` and `-fdata-sections` flags to put each function and data item into its own section to enable them to be discarded later during linking with `-Wl,--gc-sections`.
- Avoid numerical issues due to not enough stack size being allocated in matmul tests, leading to override of data buffers on L1. This is solved for now by passing large enough stack sizes for those tests. The exact stack sizes being passed are found as experimentally as the smallest multiple of 1024 that is large enough.

Enable O2 by default for Peano ukernels

---

.github/workflows/ci-linux.yml

Note: NPU reset was already disabled previously in Phoenix tests.

[CI] Disable NPU reset between runs in Strix tests

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCopyOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_copy_ops.mlir

The previous codes of `InsertCopyOpsPass` generated redundant `linalg.generic copies` as
```
scf.forall (%arg0) in (1) {
linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%1 : memref<1x32xbf16>) outs(%alloc_2 : memref<1x32xbf16, 1 : i32>) {
^bb0(%in: bf16, %out: bf16):
linalg.yield %in : bf16
}
linalg.copy ins(%0 : memref<1x32xbf16>) outs(%alloc_1 : memref<1x32xbf16, 1 : i32>)
scf.forall (%arg1) in (1) {
linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%alloc_2 : memref<1x32xbf16, 1 : i32>) outs(%alloc_0 : memref<1x32xbf16, 2 : i32>) {
^bb0(%in: bf16, %out: bf16):
linalg.yield %in : bf16
}
%base_buffer, %offset, %sizes:2, %strides:2 = memref.extract_strided_metadata %alloc_0 : memref<1x32xbf16, 2 : i32> …
```

[Softmax] Add fix to copy to destination

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/uKernels/npu4/peano/matmul.cc

This should help Peano with pipelining the matmul loops. Will report numbers based on CI run.
Latest benchmark numbers with this PR:
```
matmul4d_scale_trunci_1024_16384_512_i8_i32_O1_npu4_outline_4_level_tiling_ukernel_peano_ctrlpkt_benchmark
-----------------------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------------------------------
BM_matmul4d_trunci/process_time/real_time_mean          974 us         40.4 us            5 items_per_second=1.02679k/s
BM_matmul4d_trunci/process_time/real_time_median        974 us         40.0 us            5 …
```

[UKernel] Add pragmas to guide loop pipelining

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp

Currently, the softmax ukernel can run on a single column of 4 cores. Since there is only one parallel dimension, we'll have to modify the logic of `AssignTiles` to utilize more AIE columns.

[Softmax] Support run on a column of cores

---

compiler/plugins/target/AMD-AIE/aievec/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/aievec/test/contract_vector_to_aievec.mlir

Found missing test for `vector->aievec` path, added a test.

[--test-lower-vector-to-aievec] Add missing test from vector to aievec path for vector.contract

---

build_tools/ci/cpu_comparison/run.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/uKernels/npu1/chess/softmax.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/uKernels/npu4/chess/softmax.cc

Note that the accuracy for npu1 and npu4 are not the same, due to a different implementation of the exponential function.

[Softmax] Add chess uKernel for npu4

---

compiler/plugins/target/AMD-AIE/aievec/CMakeLists.txt
compiler/plugins/target/AMD-AIE/aievec/Passes.h

Corresponding .md file is generated in
`'~/build/compiler/plugins/target/AMD-AIE/aievec/'`

[Typo and doxygen]  Fix a typo and keep the markdown generator flag on by default.

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/uKernels/npu4/peano/trunci.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/uKernels/npu4/peano/zero_fill.cc

I think this should improve performance on the i8->i32 matmuls.

[UKernel] Add loop unrolling to peano zeroization and truncation

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir

-- This commit adds the following ops in AMDAIE dialect :-
1. amdaie.dma_start
2. amdaie.dma_bd
3. amdaie.next_bd
-- These ops are similar to what's already there in AIE dialect.
-- They are being added to AMDAIE dialect to make [DMA reprogramming](https://github.com/nod-ai/iree-amd-aie/issues/1287) work.

[Reprogramming][IR] Add dma_start + dma_bd + next_bd ops in AMDAIE dialect

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir

-- This commit adds a pass flag `reprogram-dmas` (`false` by default). When `false`,
we get a mix of npu.circular_dma_cpy_nd + npu.dma_cpy_nd ops, but when enabled/`true`,
we get only npu.dma_cpy_nd ops.
-- This is being added to AMDAIE dialect to make [DMA reprogramming](https://github.com/nod-ai/iree-amd-aie/issues/1287) work.

[Reprogram][CreateAieWorkgroup] Modify create-aie-workgroup for reprogramming Dmas

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignNpuDmaBdIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_npu_dma_bd_ids.mlir

-- This commit adds support for handling non-shim DMA ops as part of
`assign-npu-dma-bd-ids` pass.
-- This is being added to AMDAIE dialect to make
[DMA reprogramming](https://github.com/nod-ai/iree-amd-aie/issues/1287) work.

[Reprogram][AssignNpuDmaBdId] Add support for handling non-shim DMA ops

---

compiler/plugins/target/AMD-AIE/aie/test/unit_out_of_order_routing.mlir
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.cc
runtime/src/iree-amd-aie/aie_runtime/iree_aie_router.h

Background: The group ID is used inside the router, where only packet flows that share any source or destination port are assigned the same group ID. The router then restricts channel sharing to occur only within the same group, which helps prevent arbiter deadlocks.
Consider three packet flows: a, b, and c, where a and c have overlapping source or destination ports, and b is independent. The expected group IDs should be: 0, 1, 0.
However, the previous assignment logic was incorrect: `packetGroupId = std::max(packetGroupId, existingId);`, which produced the wrong results: 0, 1, 1.
This issue was observed when using out-of-order mode DMA for MatmulThinBias.

[Router] Fix packet group id assignment

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIECreateAIEWorkgroup.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_bd_ids.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_buffer_address.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_aie_workgroup.mlir

-- This commit adds a fix for handling logicalobjectfifo.from_memref to have a common logicalobjectfifo defined for any given connection as part of `create-aie-workgroup` pass.
-- This also changes `amdaie.buffer` op to have `address` attribute as `i32` instead of `ui32` to be compatible with `aie.buffer`.
-- This is being added to AMDAIE dialect to make [DMA reprogramming](https://github.com/nod-ai/iree-amd-aie/issues/1287) work.

[Reprogram] Add fix for handling Lof.from_memref + amdaie.buffer address attr as i32

---

build_tools/ci/cpu_comparison/matmul_test_config.py
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h

-- This commit adds a global flag `--iree-amdaie-reprogram-dmas` to be
used when we want to reprogram the DMAs.
-- Also adds an e2e test case.
-- This is in accordance to the [reprogramming DMA work](https://github.com/nod-ai/iree-amd-aie/issues/1287) and is the final PR to start off supporting it.

[Reprogram] Add a global flag + e2e test case for reprogramming Dmas

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignBDIDs.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeLowering.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Utils/AMDAIETransactionBuilder.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_bd_ids.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/controlcode_lowering.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/controlcode_to_transaction.mlir

This enables passing the corresponding BD IDs between paired ops, which is required for out-of-order DMA mode.

[IR] Add connection field to write_bd and dma_start ops for pairing

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIELogicalObjFifoOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt

`CopyOpInterface` is dropped in upstream (https://github.com/llvm/llvm-project/pull/157711). Move this interface to our codebase.

Bump IREE to iree-org/iree@77daeb0

---

.github/workflows/ci-linux.yml

These commands were previously used in [Phoenix tests](https://github.com/nod-ai/iree-amd-aie/blob/fc045456ada597a404370d1ba1ab0b53598c248c/.github/workflows/ci-linux.yml#L188-L191) only, now apply them to strix as well.
This change is required for the newly added Strix CI runner ([Shark-Strix-3](https://github.com/nod-ai/iree-amd-aie/settings/actions/runners/58)).

[CI] Unlimit mmap for strix tests
