compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/PassDetail.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td

This PR connects the AMDAIE backend with the common pre processing passes

[AMDAIE] Add initial common passes

---

.gitmodules
iree_compiler_plugin_group.cmake
runtime/README.md
runtime/plugins/XRT/CMakeLists.txt
runtime/plugins/XRT/runtime/CMakeLists.txt
runtime/plugins/XRT/runtime/iree-test-xrt.cc

This just has a small test to verify that we can access the XRT API

Add initial XRT runtime cmake integration

---

tests/samples/matmul_fill_spec_pack.mlir
tests/samples/matmul_fill_spec_pad.mlir

https://gist.github.com/MaheshRavishankar/3a292e77f7849f0282221a85b8a85918 is the output from using this script.
TODO : Add lit tests to verify the output.

Pad spec fuse fill and promote

---

compiler/plugins/target/AMD-AIE/air/CMakeLists.txt
compiler/plugins/target/AMD-AIE/air/ConversionPasses.cpp
compiler/plugins/target/AMD-AIE/air/TransformPasses.cpp
tests/samples/air_to_ipu_expected_input.mlir
tests/samples/air_to_ipu_flow.sh

This PR is a pruned version of my previous patch (https://github.com/nod-ai/iree-amd-aie/pull/21), where only the AIR passes essential to IREE-to-IPU e2e example is registered (please see my comments).
This PR also adds an IREE-to-AIR e2e example, with the flow summarized in air_to_ipu_flow.sh and expected input format tiled from IREE in air_to_ipu_expected_input.mlir (which I hand-modified based on previous IREE-tiled sources).
I have copied the output file of this e2e example through vitis, compiled the test and ran the test on IPU laptop, and it has passed the testbench. It would be really helpful if colleagues could try and reproduce this e2e test. Thanks.

IREE to AIR Compatibility Patch (w/ example)

---

runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt
runtime/src/iree-amd-aie/driver/xrt/nop_executable_cache.cc
runtime/src/iree-amd-aie/driver/xrt/nop_executable_cache.h
runtime/src/iree-amd-aie/driver/xrt/pipeline_layout.cc
runtime/src/iree-amd-aie/driver/xrt/pipeline_layout.h
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc

The actual executable load logic will come next.

Add descriptor set/ pipeline layout and executable cache

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

The dumped `.aiecc.mlir` file can be tested with aiecc.py directly to generate binaries.

Add input to aiecc.py as part of dumped intermediates.

---

runtime/src/iree-amd-aie/driver/xrt/CMakeLists.txt

Lets add this dependency since we do actually depend on it.

Add dependency to flatbuffer building

---

tests/samples/matmul_fill_spec_pack_peel.mlir

Note: The upstream llvm-project changes are needed to make this work. https://github.com/llvm/llvm-project/pull/74015

Add pack and peel transform spec

---

runtime/src/iree-amd-aie/driver/xrt/native_executable.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_buffer.cc

I was not building with tracing flag before. Abhishek found some bugs when building with it. This PR fixes it. Verified that the matmul still runs with it.

[XRT] fix bugs when building with tracing

---

.gitmodules
compiler/plugins/target/AMD-AIE/aie/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/BridgeToAIRPass.cpp
sync_deps.py
tests/samples/matmul_fill_static_i32.mlir

This crashes during compilation.
Requires https://github.com/spaceotter/mlir-air/tree/iree-up2

Update mlir-aie and mlir-air

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/peel_for_loop.mlir

This pass is used to peel the first iteration out of the for loop.

Add loop peeling pass

---

.github/workflows/ci.yml
build_tools/ci/pad_test.sh
build_tools/ci/rm_xclbin.sh

This works with the weird configuration on my mini-pc.

End to end CI for pad pipeline

---

tests/samples/simple_pack_pipeline_e2e.mlir

-- This commit adds lit test for linalg.matmul_transpose_b.

[AMD-AIE] Add lit test for linalg.matmul_transpose_b

---

build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

- add required passes 
- add e2e test

Vectorization on pad-pack pipeline 

---

.gitignore

See https://github.com/nod-ai/iree-amd-aie/pull/235#issuecomment-2009953221

Put previously removed .gitignore lines back

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEAttrs.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/AMDAIEUtilsTest.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/CMakeLists.txt

I guess there are 2 different things up for review here
1) unit tests for C++ code. I know that we should use lit with filecheck for testing whenever possible, because it is fast and doesn't require compiling and linking (projects where linking C++ tests are slow are a pain to work on...). There is 1 example of gtest in IREE. 
2) new algo for findLargestFactor (less important than 1).

Example of unit testing C++ code 

---

.github/CODEOWNERS

-- This commit updates CODEOWNERS' list - adds "Abhishek-Varma".
Signed-off-by: Abhishek Varma

Update CODEOWNERS in the repo

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDialect.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIETypes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/invalid.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAIRDmaToAMDAIEDma.cpp

Address https://github.com/nod-ai/iree-amd-aie/pull/267/files#r1563206551 and https://github.com/nod-ai/iree-amd-aie/pull/267/files#r1563205156

Move LogicalObjectFifoType to tablegen

---

build_tools/ci/run_matmul_test.sh

m=n=k=64 i8->i32. Numerical success!

Add int8 matmul numerical test

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEDmaOpInterface.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.h
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/CMakeLists.txt
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/invalid.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAIRDmaToAMDAIEDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/air_dma_to_amdaie_dma.mlir

Addresses: https://github.com/nod-ai/iree-amd-aie/pull/267#r1563241598

Update DoublyStridedOpInterface to include both static and dynamic access attributes

---

.github/workflows/ci.yml
build_tools/ci/run_matmul_test.sh

This PR also makes non-functional superficial improvements to the matmul test script

Bump the mlir-aie wheel used in e2e matmul tests

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
sync_deps.py

- Minor change to buildTranslationPassPipeline API

Bump IREE 

---

build_tools/ci/run_matmul_test.sh

Currently fails to compile (error message copied into test).

Add an e2e matmul transpose test 

---

build_tools/ci/run_matmul_test.sh

@yzhang93 it doesn't take as long as I expected (in the case that the tests pass). It takes about 1 minute to run these for me locally.

Add additional matmul tests 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp

The string
```
std::string newVitis = "VITIS=" + options.vitisInstallDir;
```
was being created, then pushed back into a SmallVector<StringRef>, and then deallocated, which meant that the string "VITIS=/my/path/to/vitis" was deallocated before being used, which meant it was a sequence of random chars, which meant chess couldn't be found... 
This PR changes SmallVector<StringRef> to SmallVector<std::string> so that this doesn't happen. Other strings adjusted accordingly

Fix for undefined behavior

---

experimental/delegate/mlp_aie_bf16_plugin.cpp

- Now hiding all but main "Running matmul on NPU" message
- replaced user-visible references to "AIE" with "NPU"

[Delegate] Clean messages

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerExecutableTarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETile.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
sync_deps.py

Cherry-pick of #383 from main to tresleches branch to fix broken tresleches build.
Original PR description:
Some minor API changes.

Bump dependencies 5/30/2024

---

build_tools/ci/run_matmul_test.sh

align with https://github.com/nod-ai/iree-amd-aie/pull/414

bump mlir-aie submodule

---

tests/transform_dialect/conv_fill_spec_pad.mlir

- Update the input mlir to use IR after HAL so that it won't generate the additional `memref.alloca` after bufferization.
- Update the comments for tiling which seems to be inaccurate.

Update transform dialect script for Conv2d

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Copy of the PR done in mlir-aie https://github.com/Xilinx/mlir-aie/pull/1583 before aie2xclbin was moved out of mlir-aie
Fixes https://github.com/nod-ai/iree-amd-aie/issues/468

Silence printing in aie2xclbin

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEInsertCores.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/insert_cores.mlir

-- This commit adds suppport for vector.contract in `--iree-amdaie-insert-cores`
pass.
Co-authored-by: Abhishek Varma <abhvarma@amd.com>
Co-authored-by: Vivian Zhang <vivian.zhang@amd.com>

[AMD-AIE] Add support for vector.contract in insert-cores pass

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

-- This commit adds support for vectorized matmul in `--iree-amdaie-distribute-cores-and-objectfifos` pass.
Co-authored-by: Abhishek Varma <abhvarma@amd.com>
Co-authored-by: Vivian Zhang <vivian.zhang@amd.com>

[AMD-AIE] Add support for vectorization in distribute-cores-and-objectfifo

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEDmaToNpu.cpp
compiler/plugins/target/AMD-AIE/aie/test/bad_npu_nd.mlir

Port https://github.com/Xilinx/mlir-aie/pull/1580 which fixes a bug I'm seeing in another PR (https://github.com/nod-ai/iree-amd-aie/actions/runs/9814347527/job/27101968641).

Port Xilinx/mlir-aie/pull/1580

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETargetDirect.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.h

We don't need these trampoline options anymore.

[xclbin] remove options

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

-- This commit adds ukernel support in `--iree-amdaie-distribute-cores-and-objectfifos` pass.
-- Ukernel lowering involves creation of memref.extract_strided_data ops whose outputs (base/offset) are then fed into the ukernel function invocation.
-- This commit therefore adds support for the same.

[AMD-AIE][Objectfifo] Add Ukernel support in distribute-cores-and-objectfifos

---

.gitmodules

[deps] Use shallow clone

---

build_tools/ci/run_matmul_test.sh

https://github.com/nod-ai/iree-amd-aie/pull/544 removed the dep on mlir-aie wheel and also broke peano for users (but not CI) because `me_basic.o` was in the wheel. This PR is a hotfix that downloads it from https://github.com/nod-ai/iree-amd-aie/releases/tag/ukernels on first run of the `run_matmul` script. I will send a better/more permanent fix over the weekend.

[HOT FIX] fix me_basic

---

build_tools/ci/cpu_comparison/run_test.sh
build_tools/ci/reset_npu.sh
build_tools/ci/run_matmul_test.sh

To sniff out non-deterministic NA bugs.

Increase `run_matmul_tests` repeats

---

build_tools/ci/reset_npu.sh
build_tools/ci/run_matmul_test.sh

- Only try resetting NPU when root to facilitate easier local testing when not root
- Add missing copyright header

[CI] Only reset NPU when running as root

---

compiler/plugins/target/AMD-AIE/aie/AMDAIEAssignBufferAddressesBasic.cpp
compiler/plugins/target/AMD-AIE/aie/AMDAIEObjectFifoStatefulTransform.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AMDAIETargetCDODirect.cpp
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.cc
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.h
runtime/src/iree-amd-aie/aie_runtime/mlir_aie_legacy.cc

Some accessors I missed... :crossed_fingers: no more.

Remove last bit of `AIETargetModel`

---

build_tools/ci/cpu_comparison/run_test.py

- ability to not run reset_npu.sh 
- ability to not fail with peano_commit_hash not determined
- ability to set boolean flags to false

Fixes for bugs in testing script 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/unsupported_pipelines.mlir

Before this PR, mixing thes pipelines created an uninterpretable error.

Detect and error on pipeline pairing pad-pack -> objectFifo

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp

Don't append an empty vec to smallvec

---

build_tools/ci/cpu_comparison/run_test.py
build_tools/ci/cpu_comparison/test_files/matmul_elem_2.mlir
build_tools/ci/print_ir_aie2xclbin/print_ir_aie2xclbin.sh
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/XCLBinGen.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/vectorization.mlir

Disabling vectorization at the LLVM level did the trick.
Fixes https://github.com/nod-ai/iree-amd-aie/issues/594

Fix element-wise lowering

---

build_tools/ci/cpu_comparison/run_test.py

Not sure how it happened by I managed to revert/overwrite previous changes to `run_test.py` in https://github.com/nod-ai/iree-amd-aie/pull/628. This reverts my overwriting.

Fix `cpu_comparison` test

---

build_tools/ci/print_ir_aie2xclbin/buffers_xclbin.mlir
build_tools/ci/print_ir_aie2xclbin/npu_instgen.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/PluginRegistration.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/AIETarget.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/aie_link_executables.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_logical_objectfifo_link.mlir
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc
sync_deps.py

Following changes are made
1. Some runtime API changes
2.  minor lit test fixes
3. temporary stop gap for a printer/parse issue https://github.com/nod-ai/mlir-aie/commit/527370a0d3982a20a8559944fbcaa532356b2819 that will be removed soon with an upstream fix

Bump IREE and add mlir-aie bump with a stop gap fix

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaLoopSubsumption.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/dma_loop_subsumption.mlir

I guess it's a question on where we want to lie on the spectrum A <-> B where
A: continue when anything unexpected happens in a pass
B: fail when when anything expected happens in a pass
This PR moves closer to B. Also in PR: additional diagnostics for determining why subsumption doesn't happen. 
@jtuyls I'd like to use this pass for loop subsumption of amdaie.dma_cpy_nd (currently this pass only acts on amdaie.npu.dma_cpy_nd), does that make sense? Related to https://github.com/nod-ai/iree-amd-aie/issues/619

[LoopSubsumption] Make pass fail when no device attribute available 

---

.github/workflows/ci.yml
build_tools/ci/matmul_aiert_stability.sh
build_tools/ci/print_ir_aie2xclbin/print_ir_aie2xclbin.sh
build_tools/ci/run_matmul_test.sh
runtime/src/iree-amd-aie/aie_runtime/iree_aie_runtime.cc

Bump vitis

---

build_tools/build_aietools_distro/MANIFEST.in
build_tools/build_aietools_distro/build_and_repair_wheel.sh
build_tools/build_aietools_distro/compile_test.sh
build_tools/build_aietools_distro/copy.sh
build_tools/build_aietools_distro/main.cpp
build_tools/build_aietools_distro/repair.py
build_tools/build_aietools_distro/requirements.txt
build_tools/build_aietools_distro/setup.py

Scripts to build aietools distros

---

build_tools/ci/cpu_comparison/run_test.py

@erwei-xilinx is hitting an undiagnosable error when `clang -v` is run. This PR makes the script just continue in this case, as it is not important that we get the version information.

Option to not raise exception if `clang -v` fails

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDistributeCoresAndObjectFifos.cpp

The call to replaceOp in the middle of this pass calls eraseOp, which is possibly the cause of the error observed on windows:
```
Error: <unknown>:0: error: 'arith.constant' op needs to have logic implemented for handling in distributeLocalMemory
```
In https://github.com/nod-ai/iree-amd-aie/pull/413 most of the replacements use the pattern replaceAllUsesWith, so I'm guessing it was just a mistake to use replaceOp here. 
Included in PR, a bit of code safety/sanitizing. 
Context: all this logic in distributeLocalMemory should be replaced with a robust 'privatization' pass. Basically, it's a stop gap to split the large L3 memory (describing all memories on all cores) into a local L3 memory.

[DistributeCoresAndObjectFifos][Windows flake] Don't erase op too early  

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml
build_tools/ci/build_test_cpp.sh
sync_deps.py

Linux runner started running out of disk space after I started collecting `ccache` logs.

[Hot fix] Linux CI

---

README.md

Humans probably want our history (whereas CI doesn't care)

Don't recommend depth 1 for humans

---

compiler/plugins/target/AMD-AIE/aie/AIEXDialect.cpp

Current version doesn't take into account striding (effectively assumes unit stride for all dims). Not sure how this hasn't come up before...
Thanks @erwei-xilinx

Fix `AIEX::NpuDmaMemcpyNdOp::getOffsetInBytes`

---

README.md

Nothing at all significant here. The README reads very nicely IMO but I thought I'd fix a few inconsistencies
- Text line size, where to start new line in paragraph
- Use of ':' at ends of lines preceding code lines
- Code line size, where to use \
- Some unnecessary words

[Readme] Consistency improvements 

---

build_tools/download_peano.sh

22 August to 26 September. (I thought this might fix my numerical issues (it doesn't)).

Bump peano

---

build_tools/ci/cpu_comparison/input_generator.py
build_tools/ci/cpu_comparison/run.py
build_tools/ci/cpu_comparison/test_files/conv2d_nhwc_q.mlir
build_tools/ci/cpu_comparison/test_files/matmul_f32_8_4_8.mlir
build_tools/ci/cpu_comparison/test_files/matmul_f32_8_8_4.mlir
build_tools/ci/cpu_comparison/test_files/matmul_int32.mlir
build_tools/ci/cpu_comparison/test_files/three_matmuls.mlir
build_tools/ci/cpu_comparison/test_files/two_matmul_switching.mlir
build_tools/ci/cpu_comparison/test_input_generator.py
build_tools/ci/generate_e2e_matmul_tests.py

See comments in https://github.com/nod-ai/iree-amd-aie/pull/822
@Abhishek-Varma this should unblock you (although I haven't tested your PR with this yet...)

[CI] Support bf16 output in end-to-end numerical testing 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp

This is ahead of schedule I guess but I'd like to get this PR locally https://github.com/iree-org/iree/pull/18675 (the PR built locally with no changes).

Bump IREE 10/09/2024

---

.github/workflows/ci-linux.yml
runtime/src/iree-amd-aie/driver/xrt-lite/device.cc
runtime/src/iree-amd-aie/driver/xrt-lite/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt-lite/shim/linux/kmq/bo.cpp
runtime/src/iree-amd-aie/driver/xrt/direct_command_buffer.cc
runtime/src/iree-amd-aie/driver/xrt/xrt_device.cc

Also bump MLIR-AIR to 8fe05179d83f04cf56965ae55da0f476ec7431ed

Bump IREE to 8e5f218a1d73c39ccdebb4a1d19225d5329cc6f0

---

build_tools/ci/cpu_comparison/convolution_template/convolution_generator.py
build_tools/ci/cpu_comparison/run.py

Before if you passed an invalid string for target_device, the tests passed without running anything

[Tests] Improve help and failure mode

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIENoneAccessToTemporaryBuffer.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/none_access_to_temporary_buffer.mlir

Consider the test added in this PR: it is not enough to insert the replacement alloc before any of the access ops, you will hit `operand #0 does not dominate this use` or end up with an alloc in the for loop. So this PR changes where the alloc is inserted : it is now inserted at the very start of the core's block. 
All other changes are here are tiny and non-functional (propagate op location for better diagnostics, don't do map look up twice when only once is needed, use assert instead of error if it shouldn't be reachable)

[AMDAIENoneAccessToTemporaryBuffer] Insert new alloc at block start to avoid SSA error

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/convert_core_forall_to_for.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/distribute_cores_and_objectfifos.mlir

Bump mlir-air to 3bab1025d02ffd2b14c0e887bb3749b4836936b2

Bump IREE to 5318fce9dcc809b13420ab9ff22c4c4320e26746

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEDmaUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPeelForLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEUtils.h

Chipped off from review comment in https://github.com/nod-ai/iree-amd-aie/pull/904
#include changes: include the files that are used directly not indirectly

[Utils] Finding ancestor in block 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignPacketIds.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/assign_packet_ids.mlir

Updates the packet ID assignment pass to perform assignment of packet IDs based on the source channels of the flow ops. I.e. `amdaie.flow` ops with the same source channel will get a different packet IDs assigned to accommodate multiple data packets being routed through the same ports.

[AssignPacketIds] Base packet ID assignment on source channels

---

.github/workflows/black.yml
build_tools/ci/cpu_comparison/run.py

Before pushing PRs with changes to python files, please run `black .` in the directory with the changed python files (you might need to install black). 
Black formatter: https://pypi.org/project/black/
Example of failure with unformatted file: https://github.com/nod-ai/iree-amd-aie/actions/runs/12055030579/job/33614449651?pr=939

[NFC][CI] Add check for python formatting, run black 

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertToDma.cpp

Simplification to not pass more flags into functions than are actually used (logic for pack vs unpack handled before function call).

[AMDAIEConvertToDma] Small code simplification

---

compiler/plugins/target/AMD-AIE/aievec/AIEVecOps.td
compiler/plugins/target/AMD-AIE/aievec/AIEVecTypeConstraints.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_reference_to_allocation.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_pack_into_loop.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pad.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_matmul_using_scf_forall.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir

-- IREE bump to ecd87d8680c1e79819d4b5914c092c064af32787 (2nd Dec, 2024).

Bump IREE to ecd87d8680c1e79819d4b5914c092c064af32787

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/AMDAIEOps.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/IR/test/roundtrip.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAssignTiles.cpp

Copied from aie.tile. Makes it easier to read IR.

Custom printer for tile op

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Target/mm_npu1.cc
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lowering_strategy_objectfifo_npu4.mlir

This should improve performance of matmuls with 4 tiling levels.

[PackPeel4LevelTiling] Increase the L1 K tiling size

---

.github/workflows/ci-linux.yml
.github/workflows/ci-macos.yml
.github/workflows/ci-windows.yml

Updates actions and pins as suggested by OpenSSF Scorecard, see https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.

Pin and update actions

---

compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseProducerIntoLoop.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackAndTranspose.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/bufferize_to_allocation_pack_or_copy.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/create_reference_to_allocation.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_producer_into_loop.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level1.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_and_transpose_level2.mlir
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/propagate_data_layout.mlir

The main change is to update `tensor.pack/unpack to linalg.pack/unpack` followed by upstream change  https://github.com/llvm/llvm-project/pull/123902.

Bump IREE to 055ce1f

---

build_tools/ci/cpu_comparison/run.py

I think it's easier to see at a glance what is 'interesting' about a test if all the expected defaults are not listed

[Testing] Use appropriate defaults 

---

build_tools/ci/cpu_comparison/performance_publish.py

Cosmetic improvements to the performance graphs at: 
https://nod-ai.github.io/iree-amd-aie/results_history_npu1.html
https://nod-ai.github.io/iree-amd-aie/results_history_npu4.html
1) start vertical axis at 0 us. 
2) fix 'fragmentation' caused by names changing between certain commits. 
3) Use most recent 100 commits for all tests, even if a test is new/deprecated (consistent horizontal axis). 
I've tested this change locally in a browser.

Cosmetic improvements to performance charts

---

build_tools/ci/cpu_comparison/run.py

This is due to the bugfix provided in #1176. I'll also add some performance tests in my next PR.

[CI] Enable simple control packet test on full array

---

build_tools/ci/cpu_comparison/run.py

[CI] Add packet flow performance tests

---

build_tools/ci/cpu_comparison/run.py

O2 vs O3 testing wasn't working correctly before this change.

[CI][Python] Deepcopy base dictionary, so list vals get copied 

---

build_tools/ci/cpu_comparison/run.py
build_tools/ci/run_matmul_test.sh
compiler/plugins/target/AMD-AIE/aievec/VectorToVectorConversions.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEControlCodeLowering.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEConvertToDma.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIELowerToUKernels.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEVectorization.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/lower_to_ukernel.mlir

Upstream has some changes of bufferization and vectorization APIs.

Bump IREE to iree-org/iree@ce656af8

---

runtime/src/iree-amd-aie/driver/xrt-lite/direct_command_buffer.cc

At a75d956122f2538010fa3bf52fd7d61a5b246780

Bump IREE to iree-org/iree@a75d956
